### ISSUE TITLE
[0,5] Asset info white screen

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3053] opened 2019-08-30 00:29 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://wallet.bitshares.org/#/asset/GCNY or https://develop.bitshares.org/#/asset/GCNY
2. See white screen

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/63984996-e0cabc00-cacd-11e9-89a8-55af86ed13dd.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 65.0.1

**Additional context**
GCNY is a MPA backed by GDEX.BTC

**Comment by startailcoon** [comment] 2019-09-01 18:25
Seems like a missing check. Should be a quick fix

**Comment by startailcoon** [comment] 2019-10-14 07:47
Can't reproduce any more.

**Comment by abitmore** [comment] 2019-10-14 23:30
Still white screen for me.
![image](https://user-images.githubusercontent.com/9946777/66789336-6c1bd780-eeeb-11e9-8065-be2a2bb88f50.png)

**Comment by allfory0u** [comment] 2019-10-15 06:22
I confirm this
![изображение](https://user-images.githubusercontent.com/17462020/66805288-44e5fa00-ef2d-11e9-92d9-155e7e977d1f.png)

**Comment by sschiessl-bcp** [comment] 2019-11-06 12:39
Does this reproduce if you load another page first?

Open https://develop.bitshares.org/#/market/GCNY_BTS then navigate manually to asset info of GCNY.
I still can't reproduce it :(

**Comment by abitmore** [comment] 2019-11-06 18:30
@sschiessl-bcp open a chrome incognito window, type https://wallet.bitshares.org/#/asset/GCNY directly.

**Comment by abitmore** [comment] 2019-11-19 17:31
It works now. Thanks.

**Comment by sschiessl-bcp** [comment] 2019-12-12 14:21
:P Closing it now

**Closed by sschiessl-bcp** 2019-12-12 14:21 UTC
Labels: [3] Bug, [5a] Tiny
