### ISSUE TITLE
[1] NODE up/down not really working

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#649] opened 2017-10-25 19:34 UTC
Light Client:

![](https://i.imgur.com/zBTikmL.png)

bitshares.org/wallet

![](https://i.imgur.com/AcUDdu2.png)

this whole thing is a mess to be honest.

everyone sees different nodes up/down, which should not happen based on a simple ping(?)

**Comment by tbone-bts** [comment] 2017-10-25 19:43
I get the sense this is more of a UI thing than anything else since I can't remember the last time I couldn't use the DEX due to connectivity issues.  And I haven't heard many complaints from other people, either.  Such connectivity issues seemed to clear up after the "node hopping" was implemented.  So yeah, this could be improved.  But it doesn't seem like a massive problem.

**Comment by ThomasFreedman** [comment] 2017-10-25 19:58
I suspect the issue is related to measuring the latency. Bytemaster explained to me that the method used and latency value reported by the witness_node has a significant amount of "jitter" and can vary substantially. Seems odd to me that we can't get accurate latency numbers on a network built with the graphene toolkit that requires highly accurate timing and NTP to stay synchronized.

Even the Peerplays GUI wallet has connection issues.

**Comment by btsfav** [comment] 2017-10-25 20:03
@tbone-bts considering we already paid $1500 for this specific feature already. I'd expect it to work.

ref https://github.com/bitshares/bitshares-ui/issues/49 https://github.com/bitshares/bitshares-ui/issues/110 https://github.com/bitshares/bitshares-ui/issues/346 https://github.com/bitshares/bitshares-ui/issues/376 https://github.com/bitshares/bitshares-ui/issues/486 https://github.com/bitshares/bitshares-ui/issues/531 https://github.com/bitshares/bitshares-ui/issues/574

**Comment by happyconcepts** [comment] 2017-10-25 21:10
fav is right; so much tweaking for so little gain.

As a trader I am conditioned to use red and green colors as visual cues for speed and accuracy; this screen just FUDs me up because the colors don't mean anything and I never have more than one choice on my continent for a connection to the network anyway. I feel as much love for this screen as I do for blinking text. I am sure my constructive attitude will prevail; this is not a bash, it is support for @btsfav on the merits.

**Comment by wmbutler** [comment] 2017-10-25 22:11
Unless you have a solution, I wouldn't criticise. Each attempt at a solution has led to a greater understanding. Code is iterative. I agree that it still has issues and will dedicate an hour to this for someone to research further. Here is what mine looks like from bitshares.org/wallet right now.

![screen shot 2017-10-25 at 5 11 32 pm](https://user-images.githubusercontent.com/1254810/32025915-90967e7e-b9a7-11e7-803b-262bd6740935.png)

**Comment by svk31** [comment] 2017-10-26 06:07
This is more related to how the api servers are finicky and sometimes fail than anything else. You can fail to connect to a server, then refresh and successfully connect to the same server 5 seconds later.

The websocket connection also fails more easily if you have a shitty internet connection, and nodes thst are far away, like the Chinese ones, may fail to connect in the required 5s before timeout happens. 

What Bytemaster said about latency has nothing to do with this, that's for communication between witness_node instances.

**Comment by svk31** [comment] 2017-10-26 07:38
Oh and another thing, it doesn't matter what client you use or whether it's a hosted wallet, all that matters is when the latency check is done and the state of those nodes and your own connection at that time. The latencies are not checked every single time you open or refresh the client.

**Comment by ThomasFreedman** [comment] 2017-10-26 14:38
Well svk, you know the code better than I, however when I was implementing my load balancing proxy and testing, I found the cli wallet was way more reliable and repeatable. I have never had any trouble connecting with the cli wallet, even to remote API nodes. You may be right that the cause is "finicky api servers", but if so, then why doesn't the cli wallet exhibit the same connection issues?

**Comment by wmbutler** [comment] 2017-10-27 00:31
I think it's likely there is a bug that we have been unable to uncover. I will continue to increase this bounty until it attracts someone who is willing to dig into it. Sometimes it takes a fresh pair of eyes to uncover the problem.

**Comment by ThomasFreedman** [comment] 2017-10-29 16:09
My intuition gives me the same impression Mr. Bill, and I agree, many bugs (especially subtle ones) are found by fresh eyes. Instrumenting the cli wallet's C++ code and comparing that to data produced by the javascript code may yield clues to isolate the cause of the issue. Whatever method is used, I hope the cause is uncovered by someone soon.

This is an important usability issue and directly relates to the public's impression of the wallets robustness and by implication the quality of code the BitShares devs produce.

**Comment by abitmore** [comment] 2017-10-30 18:58
@ThomasFreedman to be fair, `cli_wallet` doesn't have latency check nor built-in fail over feature, so unable to compare at all.

**Comment by wmbutler** [comment] 2017-11-06 02:21
Yeah, the cli_wallet doesn't hold open a socket either.

**Comment by svk31** [comment] 2017-11-16 12:13
I'm gonna close this since there's nothing actionable in this issue. The latency check in the light client can give different results from that of the web wallet, that's perfectly normal.

If you encounter specific bugs with nodes not working please raise new issues with concrete information.

**Closed by svk31** 2017-11-16 12:13 UTC
Labels: bug
