### ISSUE TITLE
white screen on the newest release

### ISSUE THREAD

**Issue by hubba1** [bitshares/bitshares-ui#1776] opened 2018-08-13 04:40 UTC
**Describe the bug**
 
Using release 180808
**when I sign into https://www.compumatrix.co/?r=compumatrix#  and then click on the exchange button, the page flashes and the screen turns white and freezes.  However, when I sign in with this link  https://wallet.bitshares.org/  and click on the exchange tab it goes right to the area with no white screen.
I use Windows10**

**To Reproduce**
2. Click on '....' - 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by svk31** [comment] 2018-08-13 08:02
Possible duplicate of #1770 , this is also not the place for Compumatrix issues.

**Closed by svk31** 2018-08-13 08:02 UTC
Labels: duplicate
