### ISSUE TITLE
[.5] Price column in Portfolio not displaying any values

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1264] opened 2018-03-05 23:40 UTC
Should display the unit price for a share in the chose currency.

![screen shot 2018-03-05 at 5 37 20 pm](https://user-images.githubusercontent.com/1254810/37006083-408d8e2a-209c-11e8-9030-c16b0a007ac8.png)

**Comment by svk31** [comment] 2018-03-06 07:39
Duplicate of https://github.com/bitshares/bitshares-ui/issues/1261

**Closed by svk31** 2018-03-06 07:39 UTC
Labels: bug, high priority
