### ISSUE TITLE
[2] Login issue with log in form

### ISSUE THREAD

**Issue by iamredbar** [bitshares/bitshares-ui#2410] opened 2019-01-17 02:42 UTC
**Describe the bug**
When logging in intermitently, an issue happens where the GUI will not let you type in your account name.

**To Reproduce**
1. Open desktop GUI
2. Click on text box 'Account Name'
3. Select all and start typing account name

**Expected behavior**
Always allow entering of account name.

**Video**
![login bug](https://user-images.githubusercontent.com/16945982/51291992-c7f21800-19ce-11e9-9aa6-99390bb0bbbd.gif)

**Desktop:**
 - OS: MacOS 10.13.6
 - Desktop GUI
 - Version 2.0.181212

**Additional context**
I have notice this happen in the web client as well.

**Comment by startailcoon** [comment] 2019-01-21 17:58
Do you mean it changes back while you're typing, without letting you finish?

**Comment by iamredbar** [comment] 2019-01-21 19:40
@startailcoon Yes, correct. It is an intermittent issue, doesn't seem to happen every time. While typing it will default back to the original account that was remembered.

**Comment by startailcoon** [comment] 2019-01-22 19:59
I remember noticing this myself, but never investigated it. Seem some component is updating, making the form reload to default state while you type.

**Comment by sschiessl-bcp** [comment] 2019-01-23 10:47
Duplicate of #2335

**Closed by sschiessl-bcp** 2019-01-23 10:47 UTC
Labels: [1b] User Story, [3] Bug, [4c] High Priority, [5b] Small, [7] Estimated
