### ISSUE TITLE
[2] Ignored accounts appear again after relaunch

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#48] opened 2017-01-19 20:16 UTC
_From @abitmore on March 15, 2016 8:58_

It seems current size of ignore_account_list is still too small for me? After relaunched the light client, about 10 accounts appear again, other accounts are still hidden well.

_Copied from original issue: cryptonomex/graphene-ui#781_

**Comment by calvinfroedge** [comment] 2017-08-15 19:20
@abitmore @svk31 Can we get exact reproduction steps for this issue?

**Comment by svk31** [comment] 2017-08-16 06:35
I can't help with that I'm afraid, never seen this happen myself.

**Comment by wmbutler** [comment] 2017-08-16 12:57
Closing since no further clarifications or comments.

**Closed by wmbutler** 2017-08-16 12:57 UTC
