### ISSUE TITLE
Amounts should change when clicking on the depth chart

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#566] opened 2017-10-12 01:24 UTC
When clicking on the order book, amounts and price will be automatically filled in the new order area. But when clicking on the depth chart, price in the new order area will change correctly, but amounts are either unchanged or incorrect.

**Comment by svk31** [comment] 2017-10-12 09:34
Unable to reproduce this, the amounts are always set for me when clicking a price in the depth chart. It requires you to have defined either a total or a quantity first though.

**Comment by abitmore** [comment] 2017-10-12 17:56
Yes, I mean there are different behaviors between clicking the order book and clicking the depth chart. When clicking on the order book, the amounts always be updated to total amount available on the book, no matter what has defined before.

**Comment by tximiss** [comment] 2017-11-03 07:06
For me, in Firefox the behavior is consistent.

**Comment by wmbutler** [comment] 2017-11-03 12:09
Maybe if you post a screencast for clarity.

**Comment by abitmore** [comment] 2017-11-03 13:48
I will check with latest UI when got time.

**Comment by wmbutler** [comment] 2018-01-15 02:34
Closing this since we are moving to tradingview.

**Closed by wmbutler** 2018-01-15 02:34 UTC
Labels: proposed feature
