### ISSUE TITLE
[2][gibbsfromncis] Move list of accounts from menu

### ISSUE THREAD

**Issue by 0n0t0le** [bitshares/bitshares-ui#1028] opened 2018-01-15 19:29 UTC
Many users who use the wallet model face one inconvenience: it's not convenient to view your accounts, especially if there are several of them - to change the account, you need scroll menu down to the bottom. 
For example, I have 15 such accounts. It would be much more convenient to make two independent sections: clicking on an account you'll see the choice of accounts, when you select a menu, only the menu is available. This would greatly simplify the work of users who have a large number of accounts.

Below is an example of how it might look like:

![](https://s18.postimg.org/5zt2ms16h/pic1.png)

![](https://s18.postimg.org/cq9jw96cp/pic2.png)

Thanks

**Comment by wmbutler** [comment] 2018-01-15 19:36
@Xeldal has requested this as well.

**Comment by gibbsfromncis** [comment] 2018-01-28 18:57
@wmbutler I can take this one

**Comment by wmbutler** [comment] 2018-01-28 19:22
Excellent. 

- [ ] Give the hamburger a bit more spacing so it's easy to hit.
- [ ] Include the "Accounts" option as the first selection in the accounts switcher menu. Also, remove the "Accounts" option from the hamburger menu.

**Comment by Xeldal** [comment] 2018-01-28 19:56
I think "Accounts" should stay in the hamburger. The account switcher should not start taking on "menu type" items.  It should be purely for switching accounts as a convenience not a menu. 

Keep the hamburger menu comprehensive.

For people with only a single account the switcher won't do anything.  If you add "Accounts" to the switcher it will look weird and clearly out of place with just a single menu item.

**Comment by wmbutler** [comment] 2018-01-28 19:57
@Xeldal as usual, we disagree.

**Comment by Xeldal** [comment] 2018-01-28 20:12
Obviously we disagree, and because you responded within 10 seconds of me posting.  I wonder if you gave even a moments consideration to what i said.

For 98% of the userbase with only a single account this is going to look like garbage.

Next you will start adding other account related items here and it's no longer an account switcher its a full-on fragmented menu.

**Comment by gibbsfromncis** [comment] 2018-01-28 20:15
@wmbutler if you want I can make account name not hoverable/clickable if user has no ability to add additional accounts (Idk how to detect it but I will investigate) and in this case users can find Accounts on hamburger menu.

**Comment by wmbutler** [comment] 2018-01-28 20:20
@gibbsfromncis You can detect localstorage indexdb I believe.

- If you detect it, display accounts as first item under the user
- You can leave it in the hamburger menu as well

**Comment by gibbsfromncis** [comment] 2018-01-28 20:26
@wmbutler Do I understand you correct - duplicate `Accounts` link on Accounts selection menu and Hamburger menu when user has an ability to create additional accounts?

**Comment by Xeldal** [comment] 2018-01-28 20:33
What is the purpose of duplicating the Accounts menu item?

This is a band-aid solution to a self inflicted wound.  Just leave it where it is.  No reason to have it in the switcher to begin with.

**Comment by gibbsfromncis** [comment] 2018-01-28 20:41
@Xeldal I see reasons because people who have a lot of accounts and want to manage it will have more easy way to do it without opening hamburger, scrolling down etc. 

@wmbutler hasn't approved my question yet so please do not spam here without any reason.

**Comment by Xeldal** [comment] 2018-01-28 20:48
It is the same number of steps to open the hamburger as to open the account switcher.   It in no way helps anyone manage anything.  If it is so important to have quick access to the Accounts page put it at the top of the hamburger.

**Comment by gibbsfromncis** [comment] 2018-01-28 20:50
@Xeldal Thank you. I appreciate your opinion but I'll wait for response from @wmbutler

**Comment by Xeldal** [comment] 2018-01-28 20:51
Of course.  I wasn't suggesting anything to you.

**Comment by wmbutler** [comment] 2018-01-29 05:02
@gibbsfromncis My thought process was that a user already will associate their hot-switchable accounts with the accounts dropdown menu (showing all the starred accounts in the list). It seems logic to me that the first place they would look in order to add or remove accounts in that menu would be, well, in that menu. This is why I suggested adding the accounts picker the first item inthe menu.

@Xeldal clearly feels that this will ruin the user experience beyond all recognition. I on the other hand think it's a pretty intuitive and convenient place to have it.

At this point, I guess I really don't care. @Xeldal why don't you take this over. You are so good at it.

**Comment by Xeldal** [comment] 2018-01-29 14:23
Lets go with the original suggestion. 
Move the hot-switchable accounts under the account name.  
See how that goes.

If people are losing their minds because they can't find the Accounts menu item to add/remove accounts to the list then we can address that later with solutions that don't involve fragmenting or duplicating the menu.  I have a couple more elegant ideas already if you want to here them.

**Comment by gibbsfromncis** [comment] 2018-01-29 22:10
@wmbutler 

Wallet mode:
![gif-acc-multiple](https://user-images.githubusercontent.com/35899973/35537049-254725f4-0549-11e8-94be-9afef9bbbfc0.gif)
_(padding on username when user hover was increased to make it looks better, the screen record is not up to date)_

Login/Password mode:
![gif-acc-base](https://user-images.githubusercontent.com/35899973/35537052-27e31fca-0549-11e8-8221-096e6dcd7a3d.gif)

Pull Request: #1084 

@wmbutler I have opened new issue - #1084. Our users may see this because the distance between username and hamburger was increased. If you OK with this issue please assign me to it.

**Comment by gibbsfromncis** [comment] 2018-01-29 22:18
There is the list of changes:

- if user on wallet mode he can hover on username and click to see dropdown with Account link and list of Accounts (for this mode Account link was removed from hamburger)
- if user on login/password mode he won't see anything by hovering on username. 
- Add right/left padding for username (it was 5px and looks bad when user hover, you can see this on gif above) 
- Add cursor:pointer for Lock (all clickable things should have cursor:pointer) because it was default mouse cursor
- Fix height of hamburger block (floating pixel) (on some pages when user hover on hamburger there was light line under hamburger)

**Comment by Xeldal** [comment] 2018-01-30 16:22
I can't think of any reason to have the active account duplicated in the switch list.  I would remove the active account from the list.   

(I'd also remove the "Accounts" menu item as well. It belongs in the menu)

**Comment by gibbsfromncis** [comment] 2018-01-30 16:28
@Xeldal When somebody accept my PR you can submit a new issue for that proposal.

**Comment by wmbutler** [comment] 2018-01-30 17:10
- [ ] I agree with @Xeldal that we should not display the currently chosen account in the dropdown.

**Comment by gibbsfromncis** [comment] 2018-01-30 17:17
@wmbutler okay. Will work on it.

Btw: as I see you don't practice users assigning to their issues. Can I ask you to assign me to the issues (if you are ok with it) so I can filter them by https://github.com/issues/assigned. It can help me to manage/track issues faster then always using search or tracking issues on my notes.

**Comment by wmbutler** [comment] 2018-02-01 02:21
@gibbsfromncis the problem is that until you are a member of this repo, github does not allow me to assign you directly. As such, I typically add your name in the Issue subject. Let me know if there is a better way.

**Comment by gibbsfromncis** [comment] 2018-02-01 11:49
Pull request updated: https://github.com/bitshares/bitshares-ui/pull/1084

**Comment by gibbsfromncis** [comment] 2018-02-01 18:40
@wmbutler @svk31 please close this issue as pull request was accepted.

**Closed** 2018-02-01 19:15 UTC
Labels: feature

**Comment by wmbutler** [comment] 2018-02-05 18:02
Need your BTS address for payment @gibbsfromncis

**Comment by gibbsfromncis** [comment] 2018-02-05 18:16
@wmbutler this one - https://wallet.bitshares.org/#/account/gibbs-from-ncis
