### ISSUE TITLE
[1] 404 Error When Creating New Worker Proposal

### ISSUE THREAD

**Issue by kimchi-king** [bitshares/bitshares-ui#1697] opened 2018-07-16 14:22 UTC
Whether using the desktop client or web version when you try to create a new worker proposal you get a 404 error.

1. Go to 'voting' in the menu.
2. Click on 'Workers'
3. Then click on 'Create New Worker'

**Expected behavior**
Should see the next step to create a new worker proposal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X El Capitan ver. 10.11.6
 - Browser: Chrome
 - Version: 67.0.3396.99

![screen shot 2018-07-16 at 4 21 42 pm](https://user-images.githubusercontent.com/32033560/42763816-5f41f794-8914-11e8-8947-30d3f35f36b5.png)

**Comment by svk31** [comment] 2018-07-17 03:53
Duplicate of https://github.com/bitshares/bitshares-ui/issues/1671, already fixes in develop.

**Closed by svk31** 2018-07-17 03:53 UTC
Labels: bug
