### ISSUE TITLE
[StyleGuide] Fix Popover Bottom placement 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2063] opened 2018-10-24 07:38 UTC
<img width="393" alt="screenshot 2018-10-24 10 38 01" src="https://user-images.githubusercontent.com/35899973/47414141-f027fd00-d778-11e8-9aba-e3f4214c920b.png">

**Comment by startailcoon** [comment] 2018-10-28 09:33
Duplicate of #2085

**Closed by startailcoon** 2018-10-28 09:33 UTC
Labels: [1c] Task, [3] Enhancement
