### ISSUE TITLE
[1.5][happyconcepts] More intuitive vesting BTS stats

### ISSUE THREAD

**Issue by robrigo** [bitshares/bitshares-ui#294] opened 2017-08-19 14:23 UTC
The stats shown under the "Membership" tab are confusing to me. I would expect "Pending vested fees" to match the amount of BTS I have vesting from my referee's use of the system; instead it is 0.

![screen shot 2017-08-19 at 10 21 01 am](https://user-images.githubusercontent.com/590263/29487514-6e0f0fec-84c8-11e7-81ea-24801ff2328c.png)

On the "Vesting balances" page, there are more accurate stats. Should the stats be removed from "Membership" entirely? Can we improve the intuition of these stats and unify them under one place? Perhaps there should be two tabs, one for worker pay stats and another for referral pay stats?

![screen shot 2017-08-19 at 10 21 27 am](https://user-images.githubusercontent.com/590263/29487520-789641d8-84c8-11e7-824d-227c8a1a5c90.png)

**Comment by wmbutler** [comment] 2017-08-21 14:31
Setting this as a question until we have a bit more clarification from @svk31

**Comment by wmbutler** [comment] 2017-08-31 13:32
@svk31 Need help understanding this so I can offer a solution.

**Comment by happyconcepts** [comment] 2017-09-03 00:57
Unless this is for @svk31 ...

I would be happy to scope this for clarification as I dive into graphene this weekend.

Looks like `cashback_vb`, or `pending_fees`, or `pending_vested_fees` I will dive deeper ....

**Comment by happyconcepts** [comment] 2017-09-03 00:58
![it-may-look-59ab51](https://user-images.githubusercontent.com/14145836/29999733-608bc270-9008-11e7-9bc6-00470491bba6.jpg)

**Comment by wmbutler** [comment] 2017-09-04 20:18
You've got it.

**Comment by wmbutler** [comment] 2017-09-12 20:50
@happyconcepts we are about to close out this Sprint. Will you have this complete today or tomorrow?

**Comment by calvinfroedge** [comment] 2017-09-13 16:32
@happyconcepts @wmbutler I think this issue needs more clarification, i.e. reproduction steps, and may some input from @svk31 on where the numbers come from

**Comment by wmbutler** [comment] 2017-09-13 16:40
Moving to @calvinfroedge since Sprint is being released tomorrow and no communication from @happyconcepts

**Comment by happyconcepts** [comment] 2017-09-14 13:46
@wmbutler @calvinfroedge Can I stay with this one? The testnet was bugging on me so I couldn't check the worker vesting yet ... but I got it up yesterday and there is a reset tomorrow on testnet.

**Comment by happyconcepts** [comment] 2017-09-14 14:09
I now have a few referral test accounts and I am digging into it today to see if 'graphene::wallet::vesting_balance_object_with_info' is picking up witness and worker balances too.

Different data sources for **Pending vested fees** and **Available to Claim** seems appropriate as far as the user experience is concerned. Also this reference client may have been showing two cases, pulling a single vesting balance (for referrals and fees) and pulling an array of multiple balances in the cases where a user has worker pay vesting as well as fee cashbacks vesting, they can have two different vesting balances and schedule 

Any **ideas on "Intuitive" from a UX perspective please?** Of the two types of vesting schedules (coin/days and linear/cliff)  it appears that only advanced users are going to experience linear vesting in action (for balances due to witness and worker amounts). 

Perhaps having a "basic" display and an "advanced" display is appropriate to keep the UX easier on the casual user?

@robrigo what would you expect to see, for example?

**Comment by robrigo** [comment] 2017-09-14 14:35
I think one helpful improvement from the current situation would be adding a hover-over tooltip that explains what each field means. i.e. what are pending fees vs. pending vested fees vs. vesting balance amounts.

The discoverability of these two pages is rather low IMO, and I believe it would be better overall if all of the stats were combined into one view, instead of showing "confusing" stats on the membership view. This is all my own opinion, of course. :)

**Comment by wmbutler** [comment] 2017-09-14 15:46
I think this issue just wants to display the same values if they represent the same thing. Let's keep it simple.

**Comment by happyconcepts** [comment] 2017-09-14 16:31
@wmbutler makes sense to me; let me fix this bug so it is consistent in both screens of the UI and get you a PR later today, probably missed Sigve's auto build for 9-14 though.

@robrigo I like the thought; the merrier it is in the lifetime member screen, the more lifetime members there will be imo. Perhaps the Tables rework or a "feature" issue in the near future - thanks for your feedback.

**Comment by wmbutler** [comment] 2017-09-14 16:39
You did miss the 9/14 build. We will add this into 10/01

**Comment by happyconcepts** [comment] 2017-09-14 17:31
thank you @wmbutler and good morning

**Comment by happyconcepts** [comment] 2017-09-29 17:14
I suggest that for clarity we should change the name of "Pending vested fees" to something else, primarily because these are actually instantly available cashback "fees" that are not subjected to the vesting calculations at all. Yes they are available fees, which is like vested fees, but they are not vested fees.

According to the relevant [graphene documentation about Pending vested fees](https://bitshares.org/doxygen/classgraphene_1_1chain_1_1account__statistics__object.html#a6e24bf9caed87ca04ade5361a0b2b818) the "Pending vested fees" on the `Member` screen is not supposed to be equal to Available to Claim on the `Vesting` screen.

How about "Pending Cashback Fees" or something similar? If I understand it, this data is max TTL of 2 minutes i.e. the maintenance interval so most of the time it will always show as 0.

**Comment by wmbutler** [comment] 2017-10-01 22:05
@svk31 did this get included in 171001?

**Comment by svk31** [comment] 2017-10-02 06:52
No, cause the PR doesn't really make things any clearer imo.

**Comment by happyconcepts** [comment] 2017-10-03 01:10
1) This "Pending Vested Fees' showing in the Membership UI is different; the value is independent of the vested balance/claimable value on the Vesting UI. These fees are pending, and they will be available once processed upon the next maintenance interval. But they are *not* vested.

From the documentation: `graphene::chain::account_statistics_object::pending_vested_fees` 
> these fees will be paid out as pre-vested cash-back (immediately available for withdrawal) rather than requiring the normal vesting period
So to call them "vested"  in the UI is causing confusion. 

2) What is the next step? I guess what I did was only to intentionally fix it quickly so that you could focus on more important bugs.

**Closed** 2017-10-13 08:06 UTC
Labels: bug
