### ISSUE TITLE
[3][mattbeckman] Change Node Status UP/DOWN to "Available / Currently Unreachable"

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#1004] opened 2018-01-11 10:34 UTC
When a server just has too high of a latency where the user currently is then BitShares will not connect to it but this doesn't mean the server is down. It is technically incorrect to say the server is down. This makes it appear to the user that half the servers in the network are always down which looks bad for BitShares.

I was recently in the countryside where we had very poor internet reception and I was only able to connect with 2 servers at a time at high latency. DOWN DOWN DOWN it said for most of the servers. It was me, not the network.

I think this matters because it looks bad to see DOWN in all red for lists of servers. It is more technically correct to say "Currently Unreachable". I also think the ALL CAPS is a little too strong.

I don't think "Currently Unavailable" is the best because the server is available to people who are closer to it. Sure, it is not available to the user, but there is a subtle difference where it could feel like the server is unavailable to everyone. "Unreachable" is clearly implying you personally can not reach the server (because it is too far).

I am open to discussion on this! Anyone else think changing the wording is a good idea?

**Comment by wmbutler** [comment] 2018-01-12 01:56
I agree. We still have a problem with the reporting of nodes claiming they are down when they are not. I think this is very important for someone to research. I wonder if @oxarbitrage might be interested in claiming it since a few of us have hit this without complete success. Maybe he an @xeroc could pair.

**Comment by mattbeckman** [comment] 2018-01-14 08:18
I'll handle this one

**Comment by wmbutler** [comment] 2018-01-14 21:29
Good, I really hope you can get to the bottom of this.

**Comment by mattbeckman** [comment] 2018-01-15 18:51
Screenshots of the UI changes. However, the core of the issue is likely in bitsharesjs-ws, so I'll be creating a PR over there. Currently, my thought is that it is a) concurrency issue due to rpc requests blasted out simultaneously, b) issue between browser native WebSocket and the ws npm library, or both.

<img width="1046" alt="screen shot 2018-01-15 at 10 49 25 am" src="https://user-images.githubusercontent.com/928380/34957326-fe6ef956-f9e1-11e7-8bcb-3c76aa53293d.png">
<img width="1013" alt="screen shot 2018-01-15 at 10 49 18 am" src="https://user-images.githubusercontent.com/928380/34957327-fe87600e-f9e1-11e7-90f2-bb1b6612acf9.png">

**Comment by wmbutler** [comment] 2018-01-15 19:35
@mattbeckman can you link the issue at the other repo to here so I can pay off this one? Happy to increase hours as needed.

**Comment by mattbeckman** [comment] 2018-01-18 08:13
PR for UI is here: https://github.com/bitshares/bitshares-ui/pull/1037

PR for websocket change is here: https://github.com/bitshares/bitsharesjs-ws/pull/11

I'm not 100% sure about side effects of the concurrency change, but it appeared to help for the Electron-based app. I built once without the change and once with. Someone else should test on Windows etc.

**Comment by landry314** [comment] 2018-01-19 16:17
My original issue was just about the display of the node status which has been improved (including latency values added!) but it also became about improper reporting of nodes being unavailable when they weren't. The websocket change is trying to address this, right?

Something similar was discussed in issue #649 but was never resolved.

Right now I see only one node available with medium latency in Germany and I am in New York City... is this just me? I have been getting absolutely horrible connections to nodes recently and I am wondering if it is network overload or something on my end but everything else works on my end and I was recently in Europe in many places and getting bad connections there too so I don't think it would be where I am. Maybe an issue about network overload should be opened. Maybe we need to fund some more servers somehow...

**Comment by landry314** [comment] 2018-01-19 16:38
I created this issue about the recently slow network. If I missed a related issue somewhere I would appreciate a reference there!

https://github.com/bitshares/bsips/issues/50

**Comment by mattbeckman** [comment] 2018-01-28 07:01
@svk31 disagrees that latency should be included in the UI. I guess the app used to have it, but it caused confusion, and so it was removed. If everyone agrees, we can drop the addition. If not, then perhaps we need a new term or a new method of measurement?

Since these aren't ICMP pings we're talking about, we could adjust the language from "latency" to "load". For example, low/medium latency could be combined into "Normal Load", and high latency could be changed to "Heavy Load".

Psychological impact of mostly "High Latency" across the board could be construed to end users that the "BitShares network is slow and why is nobody fixing it". However, "Heavy Load" across the board might be construed optimistically such as "woah the BitShares network is becoming more popular they should add more nodes to accommodate the growth."

Side note: node area needs a redesign. Mostly noticed it due to addition of awesome new infrastructure nodes with very long names. 😆 Hopefully it will be handled with #904 settings restyling.

Any thoughts, @wmbutler?

**Comment by wmbutler** [comment] 2018-01-28 19:28
Yes, @svk31 and I have always disagreed on this. I think latency as a number is important. It keeps us honest and provides a clear metric. I believe in transparency. We have nothing to prove by obfuscating facts.

**Comment by wmbutler** [comment] 2018-02-02 00:34
Did this get merged into 180201?

**Comment by mattbeckman** [comment] 2018-02-02 00:51
Yes, it did. Latency successfully snuck back in. 😆 Although, I should have pulled in those long infrastructure worker names before it was finalized. Some text overlap on smaller resolutions.

**Closed** 2018-02-02 23:50 UTC
Labels: bug, high priority
