### ISSUE TITLE
[0.25] develop.bitshares.org - HTLC/Direct debit - White screen

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2962] opened 2019-07-18 19:06 UTC
**Describe the bug**
White screen occurred in HTLC/Direct debit overview window.

**To Reproduce**
1. Go to [develop.bitshares.org/#/spotlight](https://develop.bitshares.org/#/spotlight)
2. Click on [HTLC](https://develop.bitshares.org/#/htlc) or [Direct debit](https://develop.bitshares.org/#/direct-debit)
3. See white screen

**Expected behavior**
No white screen

**Screenshots**
![R14KMYlje7](https://user-images.githubusercontent.com/17462020/61484705-20b76300-a9a8-11e9-88b6-2960836304ce.gif)
-------------
![image](https://user-images.githubusercontent.com/17462020/61484756-3e84c800-a9a8-11e9-9a7a-23b775942e99.png)

**Desktop (please complete the following information):**
 - Windows 7/10
 - Chrome 71 / Firefox 68
 - BitShares e60b01a

**Additional context**
Maybe related with #2817

```
BindToChainState(a) ReferenceError: "props is not defined"
    value settings.f8b09785d57ac8b3f341.js:1
    a settings.f8b09785d57ac8b3f341.js:1
    Ni vendor.717e665b38d18f9579f7.js:148
    da vendor.717e665b38d18f9579f7.js:148
    ha vendor.717e665b38d18f9579f7.js:148
    Ga vendor.717e665b38d18f9579f7.js:148
    qa vendor.717e665b38d18f9579f7.js:148
    Ka vendor.717e665b38d18f9579f7.js:148
    Ua vendor.717e665b38d18f9579f7.js:148
    ga vendor.717e665b38d18f9579f7.js:148
    enqueueSetState vendor.717e665b38d18f9579f7.js:148
    setState vendor.717e665b38d18f9579f7.js:140
    t vendor.717e665b38d18f9579f7.js:32
    _loadModule vendor.717e665b38d18f9579f7.js:32
    a vendor.717e665b38d18f9579f7.js:132
    N vendor.717e665b38d18f9579f7.js:132
    u vendor.717e665b38d18f9579f7.js:45
 
Object { componentStack: "\n    in a\n    in StatefulaContainer\n    in div\n    in div\n    in t\n    in div\n    in t\n    in a\n    in BindToChainState(a)\n    in r\n    in StatefulrContainer\n    in n\n    in t\n    in t\n    in div\n    in div\n    in div\n    in div\n    in BodyClassName\n    in div\n    in t\n    in t\n    in withRouter(t)\n    in t\n    in t\n    in IntlProvider\n    in t\n    in t\n    in StatefultContainer\n    in Unknown" }

```

**Comment by startailcoon** [comment] 2019-07-21 17:41
Missing prop!

**Comment by react-cat** [comment] 2019-07-25 15:18
@startailcoon Can I claim this task ? 
I reproduce it and found places which causes that error in DirectDebitModal, and also we have same issue in DirectDebitClaimModal. 
Also since this components use getInitialState which is deprecated, they are need a little refactoring

**Comment by allfory0u** [comment] 2019-07-25 15:27
@react-cat
But we already have PR blockchainprojects#164

**Comment by startailcoon** [comment] 2019-07-25 21:16
@react-cat it's already assigned to @sschiessl-bcp, please post your findings to the attached PR so it can be checked on.

**Comment by react-cat** [comment] 2019-07-26 11:59
@startailcoon Sorry, found this issue 4 days ago before sschiessl-bcp assigned it to himself and didn't notice that when I come back to this task.
The task done in the same way as I would done it, except removing deprecated method, so no need to post any findings.

**Closed** 2019-07-26 12:53 UTC
Labels: [1b] User Story, [3] Bug, [4c] High Priority, [5a] Tiny
