### ISSUE TITLE
180201 version, clicking "Hidden" hangs the client & memory leaks then

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#1109] opened 2018-02-03 09:22 UTC
win7, latest client. on clicking "Hidden" in portfolio, client stops working, and leaks memory / drains all my CPU kernels.

**Comment by wmbutler** [comment] 2018-02-04 18:44
I have the same issue when switching accounts. Also documented here: #1100 This is a serious bug and I'm certain is causing issues for many.

**Comment by wmbutler** [comment] 2018-02-04 19:26
@btsfav are you referring to the latest lite wallet or the web version?

**Comment by btsfav** [comment] 2018-02-05 08:50
@wmbutler sorry, I only use the light client

**Comment by wmbutler** [comment] 2018-02-05 18:07
I've asked @svk31 to carefully examine things. I think this is affecting some (like us) more than others. But I cannot seem to pinpoint the cause.

**Comment by wmbutler** [comment] 2018-03-01 20:20
Likely fixed in 180301 release.

**Closed by wmbutler** 2018-03-01 20:20 UTC
Labels: duplicate
