### ISSUE TITLE
[3.1.190618.2-rc1] - White screen after login in standard mobile browser

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2939] opened 2019-07-12 20:56 UTC
**Describe the bug**
White screen after logging into your account in a standard Android browser

**To Reproduce**
1. Go to [staging.bitshares.org](https://staging.bitshares.org/#/)
2. Log in to your account
3. See white screen

**Expected behavior**
Don`t see a white screen

**Screenshots**
![ezgif-3-75d15b4e329c](https://user-images.githubusercontent.com/17462020/61157692-8e264800-a4ff-11e9-8105-629da73e4e31.gif)

**Smartphone (please complete the following information):**
 - Android 5.1.1 (MIUI Global 7.2) 
 - Standard browser v10.4.5

**Additional context**
Android 9 and Chrome/Firefox work well.

**Comment by allfory0u** [comment] 2019-07-12 21:01
Due to this, I can not continue testing

**Comment by startailcoon** [comment] 2019-07-13 14:37
Can you supply any debugging from your browser that can be used to track the cause of this?

**Comment by allfory0u** [comment] 2019-07-13 15:19
@startailcoon No, unfortunately, I can't get any debug information from this browser

**Comment by startailcoon** [comment] 2019-07-14 09:55
Closed as browser will be regarded as unsupported.

**Closed** 2019-07-14 09:55 UTC
