### ISSUE TITLE
[2.5][react-cat] Replace Explorer/Markets old components to ant (abandoned)

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1963] opened 2018-10-09 18:37 UTC
Requested estimate: 6h

**Comment by startailcoon** [comment] 2018-10-13 09:04
I'm sure you're aware of it, but do note that the same component is used on the Exchange section.

**Comment by react-cat** [comment] 2018-11-26 12:06
@gibbsfromncis I make a review and suggested that this task can be done in 12 hours. Can I claim it ?

**Comment by startailcoon** [comment] 2018-11-27 16:20
@react-cat I'm bouncing this task to 12 hours after discussing the issue range with @gibbsfromncis that is most familiar with the ANT components. This task is large and I hear you're awesome at ANT ;)

Please report back if you find the task being to large, but the hours should cover your main development hours. Learning the bases is included in this.

Make sure you're getting familiar with how the application works, either by conversing with @gibbsfromncis, me, or the rest of the team.

Good luck with your first major task.

**Comment by react-cat** [comment] 2018-11-28 12:45
@startailcoon Thanks !

**Comment by wmbutler** [comment] 2018-12-15 20:30
@react-cat moved this to January. Are you on it?

**Comment by react-cat** [comment] 2018-12-19 11:16
@wmbutler Yes, sorry for late response

**Comment by startailcoon** [comment] 2019-02-12 12:43
Moving this upwards to next month. @react-cat, still want to work on this?

**Comment by react-cat** [comment] 2019-02-16 21:23
@startailcoon Yes, I just returned to work

**Comment by startailcoon** [comment] 2019-04-14 18:02
@react-cat do you have a progress report on this task?

**Comment by react-cat** [comment] 2019-04-14 19:34
@startailcoon A part of task is already done, currently I met next issues.
 AssetSelector component is used in Exporer/Markets -> find markets page. That component needs to be replaced with an ant components. AssetSelector was already replaced by AssetSelectorStyleGuide in #1927, but after my review, firstly it was replaced with AssetSelectorStyleGuide in #2099 PR, but then as states in [this](https://github.com/bitshares/bitshares-ui/pull/2099#issuecomment-437591964) comment, another PR was created #2142, and AssetSelectorStyleGuide wasn't there. 

Now it called AmountSelectorStyleGuide and doesn't work as expected, despite of the fact that task #1927 was to replace AssetSelector, not AmountSelector.

Due to this issue I can't just replace AssetSelector with AmountSelectorStyleGuide and this issue block me. 

Currently I am working on another part of this task, and was just about to write you. 
The problem is that ANT table require only an object with set of data and some configs for sorting etc. to render a table, but in current version, not all data gathered up before render, some data is gathering while rows are rendering. 

Due to this and some other specifics in code, table render process needs to be rewritten from scratch with use of a little pieces of old code. I can extend my answer with code samples or anything else.

I need your approve to start rewriting table render process, cause it may take more time than estimated.
And also about AssetSelector, replacement of AssetSelector with ant components is not a part of this task, so I think we should discuss what to do about it

**Comment by OlegBrazhnichenko** [comment] 2019-04-17 10:47
@startailcoon Need your approve to rewrite table render to continue work on this task

**Comment by react-cat** [comment] 2019-04-17 10:48
@startailcoon Need your approve to continue work on this task

**Comment by startailcoon** [comment] 2019-05-06 18:22
Sorry for the late reply @react-cat. Right now I think it's better to stage the work you have completed and leave this, quite large, issue as it is. We could file it under a new issue to be looked at on a later state.

**Comment by react-cat** [comment] 2019-05-10 15:28
@startailcoon I pushed to my fork what I currently done. I spent up to 8 hours on this work. Most of that time I spent on research how table is currently implemented and how to replace it with ANT table and now I know how to replace it. 

Considering that task wasn't completed it's ok if you would compensate only a part of my time or wouldn't compensate time at all. 

I would like to continue this task in future, when you decide to replace this table with ANT table so that my efforts were not in vain

**Comment by startailcoon** [comment] 2019-05-12 09:28
Sorry for the delayed response @react-cat. As the work involved is to much in contrast to how much we gain from it, I'd suggest we abandon it for now. What we have today doesn't require us to move to the new style-guide to work, though it would be nice at some point get it fixed. I also think we should concentrate on other issues.

You're a new developer to the UI, so I think you've learned a lot going through the code for this task. I'd like to offer you a compensation of 2.5 hours for the time of investigating and working thus far.

**Comment by react-cat** [comment] 2019-05-13 22:12
@startailcoon Okay, that's fine. 
I'm new to the UI, but I spend enough time to figure out how to make this task done and on my estimate it will took not longer than 20 hours in total including those 8 that I already spend, so just keep in mind that I want to finish this task in future if it would be needed.

**Comment by startailcoon** [comment] 2019-05-22 18:23
@react-cat feel free to discuss any other issues that we could assign you in the future as well.

**Closed by startailcoon** 2019-05-22 18:23 UTC
Labels: [1c] Task, [3] Enhancement, [5e] Huge, [7] Estimated
