### ISSUE TITLE
[6] Unable to broadcast transaction when account does not contain BTS or UIA BTS fee pool is empty

### ISSUE THREAD

**Issue by testlump** [bitshares/bitshares-ui#201] opened 2017-07-21 23:14 UTC
**Issue Description**
------------------------
When attempting to use a User Issues Asset (OPEN.BTC in this case) to pay the network fee where no other assets exist on an account, the transaction fails to broadcast with the following error:

![image](https://user-images.githubusercontent.com/29457910/28484899-221842fa-6e6d-11e7-844b-89024fe70c52.png)

Prior screens indicate that the fee payable in the UIA (OPEN.BTC) should be acceptable: 

![image](https://user-images.githubusercontent.com/29457910/28484815-8d2d9da2-6e6c-11e7-9ea0-d0bba6d79e5d.png)

However the confirmation dialog lists the fee in BTS:

![image](https://user-images.githubusercontent.com/29457910/28484883-0498ad46-6e6d-11e7-9f86-2446986b583f.png)

The problem is apparently because the fee pool of the UIA does not contain any BTS to convert part of the UIA to BTS in order to fund the network fee. The problem here is a case of chicken and egg. A new user will use a gateway to obtain a UIA on the DEX possibly with the intention of converting that UIA to BTS but then either because they have no BTS in their account or the issuer of the UIA has no BTS in their fee pool, the user is effectively trapped and can perform no action until they fund their account with some BTS. 

From @taconator on [BitsharesDEX (Telegram)](https://web.telegram.org/#/im?p=@BitSharesDEX)

> Yes you can still pay the fee in whatever asset you want.

> The only condition is that the issuer of the asset must have enough BTS in its fee pool to automatically perform the conversion.

**Expected Behaviour**
------------------------ 
The fee should be payable in any asset the user holds *or* the network should permit some number of rate limited free transactions to allow assets for which the fee pool has not been replenished to be traded or transmitted to a user / gateway or bridge. 

A human readable error should be displayed.

**Steps to reproduce** 
------------------------

This relies on the fee pool for the asset being empty as appears to be the case at the time of reporting for OPEN.BTC)

1) Configure a new empty account in the Bitshares light wallet (https://bitshares.org/download) 
2) From the "Deposit/Withdraw" tab, choose Transfer Service: "Openledger (OPEN.X)" and then "Gateway"
3) From the drop-down choose BTC 
4) Deposit ~10 USD's worth of BTC to the address provided

** Wait for OPEN.BTC to be credited **

5) Navigate to the Exchange tab and choose **MY MARKETS** --> **BTC** --> **BTS** for the **BTS:BTC** trading pair

6) Place an order for BTS for approximately half the value of OPEN.BTC in the account and click **BUY**
7) Confirm the order
8) **bitshares-crypto** digest error is displayed (see first screenshot)

If a deposit of BTS is made to the account to cover the network fee, the transaction is broadcast without a problem.

**Comment by landry314** [comment] 2017-07-22 09:27
does bitshares core not allow a delay to pay the fee? if the fee could be paid AFTER the exchange to BTS (or a BTS asset) instead of before, then the problem would be solved!

or the network could loan the fee if the balance is zero, use it to pay and have the loan paid back. i don't know the limitations of bitshares here.

i had this problem once before too just because my BTS was all in open orders and i was trying to sell BTC. i could not understand the human unreadable error until my friend sent me 2 BTS to fix my problem. we later realized i could have canceled my BTS sell order also.

**Comment by wmbutler** [comment] 2017-07-23 16:19
I think the solution here is to create a very clear error message. Additionally, we know ahead of time if the user has no BTS so we should manage it accordingly. We should disallow the trade execution button when we know the trade will fail.

**Comment by landry314** [comment] 2017-07-23 23:26
if you disallow the trade execution button then there needs to be an explanation right there as to why or people will get very frustrated.

the problem goes much deeper than an error message. the problem is that people trying to fund their EMPTY wallet with BTC with NOT BE ABLE TO. this is a HUGE problem. if people migrate their crypto funds to this new awesome Bitshares system they just heard about and the first thing they encounter if the inability to deposit it due to not having any BTS, they will just get angry and think bitshares doesnt work right.

i started my account with BTS someone gave me. i dont even know how i would have otherwise. how do people start their accounts without BTS anyway???

**Comment by wmbutler** [comment] 2017-08-04 17:03
I think this needs a two-pronged approach. I think we've identified that the core problem is caused by UIA issuers who fail to keep their pools funded. 

- While we all agree that UIA creators should be responsible, a notification system would go a long way towards solving this. Ideally, the blockchain could send a transaction to the UIA creator with a memo indicating that the pool is getting low.
- Another more aggressive technique that I would advocate would be a provision allowing new accounts / adopters to have their trades paid by a faucet for their first 10 trades or so. This would eliminate a bad experience, which reflects poorly on the entire BTS ecosystem.
- Lastly, once that new user has run through their 10 'free' transactions, they could be made aware that they need to notify the UIA creator that the fee pool is empty.

Most importantly, we already know prior to the user clicking the buy/sell button, the status of the UIA pool. It is silly for us to lead the user down a dead-end path and we should use all tools at our disposal to make this process a better experience for the user.

**Comment by happyconcepts** [comment] 2017-08-04 18:19
What if an error messaging simply showed the reason for the broadcast
failure in a UX'd manner?

"Not enough BTS for this transaction. Click here to deposit bitcoin."

Also in general I do not favor changes just to babysit for derelict or
distracted coin issuers...that seems like a slippery slope.


On Aug 4, 2017 10:03 AM, "Bill Butler" <notifications@github.com> wrote:

I think this needs a two-pronged approach. I think we've identified that
the core problem is caused by UIA issuers who fail to keep their pools
funded.

   - While we all agree that UIA creators should be responsible, a
   notification system would go a long way towards solving this. Ideally, the
   blockchain could send a transaction to the UIA creator with a memo
   indicating that the pool is getting low.
   - Another more aggressive technique that I would advocate would be a
   provision allowing new accounts / adopters to have their trades paid by a
   faucet for their first 10 trades or so. This would eliminate a bad
   experience, which reflects poorly on the entire BTS ecosystem.
   - Lastly, once that new user has run through their 10 'free'
   transactions, they could be made aware that they need to notify the UIA
   creator that the fee pool is empty.

Most importantly, we already know prior to the user clicking the buy/sell
button, the status of the UIA pool. It is silly for us to lead the user
down a dead-end path and we should use all tools at our disposal to make
this process a better experience for the user.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitshares/bitshares-ui/issues/201#issuecomment-320301189>,
or mute the thread

**Comment by testlump** [comment] 2017-08-04 18:31
The problem with prohibiting any sort of gratis transaction is how you deal with fee pools that are empty but for which the issuer cannot - for a potentially legitimate reason (holiday, afk, accident etc) - fill? 

We saw this with Openledger OPEN.BTC - the UIA was not tradeable if you had no BTS in your account for upwards of 24 hours. It was an accident in this instance and the pool was temporarily replenished by a member of the BTS community. Similar instances may be equally benign. 

The question should be; what do centralized exchanges do? They certainly don't block the trading of listed assets even if the issuer has been derelict in the performance of their duties. 

Striking a balance between usability and penalization seems reasonable. Listed assets should be tradeable for free (via faucet up to some limit) for users who hold no BTS in their accounts. 

Bill Butler suggests 10 free tx's (per asset or per account is another question) and this seems reasonable if also coupled with adequate notifications of the source of the issue, the remaining free transactions and who to query for fee pool replenishment.

**Comment by happyconcepts** [comment] 2017-08-04 18:56
I remain unconvinced. You are introducing a precedent of free transactions,
with a potentially negative consequence to network fee revenue.

When I am still looking at untouched (reference?) debugging error messaging
in the UI...why are you de-valuing bitshares?

**Comment by testlump** [comment] 2017-08-04 19:10
How does providing a usable experience via limited free transactions to users (typically new users) who do not hold Bitshares _de-valuing bitshares_?  There has been no suggestion of providing limitless free transactions.

Centralized exchanges permit users to trade in any listed asset that they hold - what would be the benefit of the DEX adopting a non-standard model requiring BTS *and* _listed asset_ before trade is permissible?

**Comment by happyconcepts** [comment] 2017-08-04 21:44
You missed this part:
When I am still looking at untouched (reference?) debugging error messaging
in the UI.


On Aug 4, 2017 12:10 PM, "testlump" <notifications@github.com> wrote:

How does providing a usable experience via limited free transactions to
users (typically new users) who do not hold Bitshares *de-valuing bitshares*?
There has been no suggestion of providing limitless free transactions.

Centralized exchanges permit users to trade in any listed asset that they
hold - what would be the benefit of the DEX adopting a non-standard model
requiring BTS *and* *listed asset* before trade is permissible?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/bitshares/bitshares-ui/issues/201#issuecomment-320330539>,
or mute the thread

**Comment by testlump** [comment] 2017-08-04 21:53
While the message needs addressing (it's in the original bug report), how does changing the message the user sees alter fact that the user cannot transact if they have only assets in their account that have no Bitshares tokens in their fee pool(s)?

**Comment by happyconcepts** [comment] 2017-08-04 22:50
Your question is better directed to bitshares-core I think. Xero, Ox, etc.

My point is, you only need to fix the messaging to solve this UI issue
sufficiently. The rest is inappropriate feature creep. I
 believe bytemaster would agree.

Second point: bitshares is an ecosystem and should remain open enough to
support many businesses....including those business models that may not
benefit from giving away 10-free transactions.

What you propose will arbitrarily  limit the scope of the businesses that
can be conceived, built, and run successfuly on bitshares.

If you need a bot to rtfbc for you and add more funds to your MPA or UIA
fee pool while you are on vacation please message me.

**Comment by wmbutler** [comment] 2017-08-07 22:47
I could be swayed either way on this topic. Probably the most responsible way to handle this is to ensure:

- UIA pools are all funded
- The end user understands who is responsible for their failed transactions and who to contact in order to resolve the issue.

**Comment by svk31** [comment] 2017-08-15 14:06
I can add an error message when the pools are empty and the user has no other balance to use, it requires some code to be added to bitsharesjs.

**Comment by wmbutler** [comment] 2017-08-15 14:27
I think it would be best to notify the user prior to the buy/sell operation by presenting the message prior to the user initiating the buy/sell.

![screen shot 2017-08-15 at 9 26 23 am](https://user-images.githubusercontent.com/1254810/29320157-ec7845ea-819b-11e7-9d74-21b0f95e3682.png)

**Comment by btsfav** [comment] 2017-08-16 06:08
@wmbutler how about adding an addtional link with 

"Click Here to buy BitShares (10 BTS ~ 50 Transactions)"

link it to shapeshift (referral?) and prefill bitshares user name. 

referral income should be forwarded to the dev fund

**Comment by wmbutler** [comment] 2017-08-16 12:58
Out of scope in my opinion. Open a separate issue.

**Comment by svk31** [comment] 2017-08-17 07:06
@wmbutler I like the error message mockup, but don't you think the user would still like to know how much BTS they actually need to pay that fee so they can go get it somewhere?

**Closed** 2017-08-17 10:27 UTC
Labels: bug, high priority, question

**Comment by btsfav** [comment] 2017-08-17 10:51
I still think it would make sense to add a direct method to buy btishares within this error.

it's in-scope in my opinion

**Comment by wmbutler** [comment] 2017-08-17 14:34
Maybe something like this then? Still think that users can handle purchasing BTS without additional prompting. This issue is more about improving the error reporting rather than facilitation the purchase.

![screen shot 2017-08-17 at 9 33 36 am](https://user-images.githubusercontent.com/1254810/29417587-4b55481c-832f-11e7-9819-f1fe92a42983.png)
