### ISSUE TITLE
Very big amount numbers on transaction confirmation page

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1293] opened 2018-03-10 20:18 UTC
Steps to reproduce: open https://wallet.bitshares.org/#/account/committee-account, click "Margin Positions", click "X" under "close", input password to unlock local wallet.

![image](https://user-images.githubusercontent.com/9946777/37246353-225accf0-24a8-11e8-88d0-7c765d7c96be.png)

By the way, don't tell me that we should simply remove the 'X' buttons because I'm not on my own account. Please check #1285.

**Comment by startailcoon** [comment] 2018-03-10 22:09
Duplicate of https://github.com/bitshares/bitshares-ui/issues/1194

**Closed by startailcoon** 2018-03-10 22:09 UTC
