### ISSUE TITLE
[.5] Don't Place Yellow Margin Calls In The Order Book If They Can't Be Bought

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#877] opened 2017-12-15 21:31 UTC
Margin calls get placed in the order book as yellow orders but they can't be bought. I think there are some conditions not being met for them to be bought.

All orders in the order book need to be purchasable.

If there is an unbuyable order in the order book then clicking on "lowest ask" before you place a buy order no longer works as intended because it would create a price which would not execute.

Yesterday there were yellow margin call orders sitting there for at least 30 minutes. It is confusing and annoying and serves no purpose. If there are orders about to be buyable then they need to not be in the order book until they are. If it is just informing the users then it shouldn't be in the order book.

**Comment by landry314** [comment] 2017-12-15 21:33
This is an actionable version of #876.

The action, @wmbutler, is to not place them in the order book until they are actually buyable.

**Comment by btsfav** [comment] 2017-12-15 21:35
disagree, information is needed act accordingly. and margin calls are orders regardless

**Comment by landry314** [comment] 2017-12-15 21:38
It confuses users to have sell orders you can't buy... the calls are already displayed in the top bar above the chart.

What about the "Lowest Ask" problem? Let's at least have it skip the unbuyable orders. These yellow orders are breaking the quick-fill lowest ask function.

**Comment by HarukaMa** [comment] 2017-12-16 06:50
I agree that lowest ask being affected by it is annoying. I think it should always be lowest buyable order, skipping margin call order if needed.

Dunno if it's viable on frontend though.

**Comment by HarukaMa** [comment] 2017-12-18 19:01
After observing the market for a while and reading on how margin call order works, I think:

1. We certainly should not remove the margin call order from the order book, as it has important information on the order size which traders need to know. Having a multiple-digit or a very small call order pending means different things.

2. If I understand the margin call process correctly, the call order will only execute between call limit price and margin call price as shown above the chart. Thus I think _it is possible_ to skip the margin call order in "Lowest Ask" field when current highest bid order is above the call limit price, as in this situation the margin call order cannot be executed. If the margin call order get executed in the price range and still remaining, it's safe to put that order into "Lowest ask" as you can buy at that price now.
(Exchange the "bid" and "ask" above if you are observing the market in reversed way as I do.)

**Comment by landry314** [comment] 2017-12-21 05:51
Why doesn't it just execute then? There are orders that can fill it.

Also, it doesn't just confuse the Lowest Ask, it also changes the TOTAL column on the right to make it seem like clicking on that order will fill more volume than it does.

**Comment by HarukaMa** [comment] 2017-12-21 06:19
@landry314 There _are_ requirements have to be met to execute margin call orders. That's by design to make those orders execute at a reasonable price. If the market is trading at 1.1 and a margin position has call price of 1.0, you won't want the margin call order to execute at current market price.

I'm using the layout without "total" column so didn't notice that. But I agree that it should not be affected too.

**Comment by landry314** [comment] 2018-02-01 20:30
People are confused about this on the telegram groups. An order in the order book which is not YET buyable is confusing. No exchange would ever do this except the DEX... It is just weird.

**Comment by landry314** [comment] 2018-02-01 20:55
I just got a warning that my order was 1.21 times higher than the lowest ask... because of one of these unbuyable yellow orders...

WE HAVE TO SEE THIS AS A BUG!

**Comment by wmbutler** [comment] 2018-02-02 00:40
I wouldn't call it a bug because it's working as **someone** intended. But agree that it's not perfect.

**Comment by landry314** [comment] 2018-02-02 02:23
I meant the bug was seeing the warning due to the lowest ask being the yellow order and 1.21 times lower than the real lowest ask. This is not an intended result.

The total column gets thrown off too and the quick-click lowest ask feature becomes broken.

That is three bad results of this intended decision... So, yeah, I am glad you added a fix to the milestone! Thanks.

**Comment by landry314** [comment] 2018-02-02 02:24
I guess a discussion is in order about how to make this work better then a bounty set?

**Comment by wmbutler** [comment] 2018-02-02 23:50
The issue is pretty clear, whether to display this in the order book or not.

**Comment by landry314** [comment] 2018-02-03 14:16
I agree, just thought you would want to display it somewhere else or something.

**Comment by HarukaMa** [comment] 2018-02-03 14:22
Consider #920 for it? Although the settle orders are already moved, where to put call orders should be reconsidered.

**Comment by wmbutler** [comment] 2018-02-04 18:40
Moving to proposed feature until someone can suggest a good location.

**Comment by abitmore** [comment] 2018-02-05 03:30
Won't be an issue after next release of bitshares-core.

**Comment by wmbutler** [comment] 2018-02-05 18:08
OK, closing based on this information.

**Closed** 2018-02-05 18:09 UTC
Labels: invalid
