### ISSUE TITLE
[1.5][nbcks] Navigating to Market BTS/bitSEK Issues

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1041] opened 2018-01-18 19:36 UTC
Navigating to the bitSEK market results in the following error in the latest version of the client.

It was working at first, but something has made this market unable to load. 

The wallet page wallet.bitshares.org works though. 

![image](https://user-images.githubusercontent.com/12114550/35117531-2e464a6c-fc8f-11e7-9206-f7bb029f6c37.png)

**Comment by wmbutler** [comment] 2018-01-19 04:48
Can you consistently reproduce this for just this market?

**Comment by startailcoon** [comment] 2018-01-19 10:46
I consistently had this issue for this very market several time, even after restart of software and computer. I will follow up today if the issue persists.

**Comment by startailcoon** [comment] 2018-01-19 16:02
The issue still persists on my installed version of the wallet.

**Comment by nbcks** [comment] 2018-01-24 19:35
Could I claim this issue please?

**Comment by nbcks** [comment] 2018-01-27 17:11
@startailcoon which version of the wallet exactly were you using please?

**Comment by startailcoon** [comment] 2018-01-29 06:51
Latest, 2018.01.15

**Comment by nbcks** [comment] 2018-01-29 20:21
Ah okay I've reproduced it great

**Comment by startailcoon** [comment] 2018-02-19 12:30
What did your search give as the issue for this?

**Comment by nbcks** [comment] 2018-02-19 15:07
It's a very difficult issue to debug since the bug happens so sporadically. Most of the time it works, but sometimes it random comes up. 

It's not to do with the market price not existing, as other assets have that and don't crash.

**Comment by wmbutler** [comment] 2018-02-21 19:07
Added an hour to accommodate additional research.

**Comment by wmbutler** [comment] 2018-03-01 20:23
Closing this. Will re-open if someone decides to work it.

**Closed by wmbutler** 2018-03-01 20:23 UTC
Labels: bug
