### ISSUE TITLE
[0.25][svk] Exchange "My Open Orders" not updated properly in certain cases

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#578] opened 2017-10-14 17:50 UTC
I stumbled upon a strange issue with the exchange tables.

I placed a buy order on 0.01 bitBTC and later on placed another buy order of 0.01 bitBTC again. Same amount, same buy price.

I expected the "My Open Orders" on the asset exchange tab to update to 0.02, but it does not.

## On the assets "My Open Orders"
![image](https://user-images.githubusercontent.com/12114550/31577904-fd2f68fa-b116-11e7-9ea8-1e38ea4ca32e.png)

## On my account page
![image](https://user-images.githubusercontent.com/12114550/31577909-09fa9352-b117-11e7-984d-5247a487c0fa.png)

## On "My Open Orders" for the account
![image](https://user-images.githubusercontent.com/12114550/31577998-e638eff2-b118-11e7-8555-816a67a8f8a7.png)

I've tried reloading the page with F5 within the wallet, but it still sais the same wrong value for my open buy orders on the assets page.

I assume it doesn't summarize the orders properly in the open orders table on the asset.

Running `Bitshares.171009`
Connected to: `wss://eu.openledger.info/ws`

**Comment by startailcoon** [comment] 2017-10-14 18:48
Related to #505

**Comment by svk31** [comment] 2017-10-15 09:01
You're right this is a probably a duplicate of #505, but with a clearer explanation so I was able to reproduce it.

This was an extremely strange bug, since the code as is for some reason does not produce the expected result, it might even be a bug in Immutable.js. The fix was to convert the orders array to a regular js array before using map to produce, even though that really should not matter..

**Closed by svk31** 2017-10-15 09:01 UTC
