### ISSUE TITLE
Login restoring from a back up key - double loads chose a file twice

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2471] opened 2019-02-17 13:43 UTC
**Describe the bug**
Please see #2301
First time browser user experience emulates the same login behavior seen in #2301 of double loading the key upload after clicking open once already. Duplicated in the past with Opera, Google, Firefox (iirc), Brave.

**To Reproduce**
1. Browser login as if first time use or new device
2. Enter account name (local)
3. Scroll down and click to upload a back up BIN file
4. Select BIN file from storage device and location, click open
5. See error of double load - same request as before - BIN file name and location
6. Re-enter the BIN file name and location; click open
7. Entering password should allow account entry however, that login bug is a terrible first time user 
    experience without ever experiencing any of the features of the platform.

**Expected behavior**
No login double load

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600 
 - Version: 190207-rc3

**Additional context**

First time use - Last 20 logs

log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
error:  request timed out after 3000ms with object ids: ["Your Account"]
error: checkFeeStatusAsync errorundefined
log: Your node is out of sync since 5.400000095367432 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 4.296999931335449 seconds, waiting 10 seconds, then we notify you
log: Error: Blocktime not available right now
error:  request timed out after 3000ms with object ids: ["checking.Your Account"]
log: Your node is out of sync since 5.27400016784668 seconds, waiting 10 seconds, then we notify you
log: Error: Blocktime not available right now
log: 1347mshtml2canvas (168fb8180c8):Canvas renderer initialized (1679.015625x493.03125 at 0,0) with scale 0.6666666865348816
log: auto locking after600s

**Comment by sschiessl-bcp** [comment] 2019-02-19 10:33
Duplicate of #2301

**Closed by sschiessl-bcp** 2019-02-19 10:33 UTC
