### ISSUE TITLE
Possible serious mistake of the system in a sale

### ISSUE THREAD

**Issue by clgc1972** [bitshares/bitshares-ui#2505] opened 2019-03-01 11:29 UTC
Good morning,
For about a week, I am waiting to solve a serious problem due to a sale that I made from my account from bitusd to bts with all my funds and that has inexplicably been lost. 

What I want to say, is that the amount of BTS has not appeared since more than approximately 2245 bitusd to exchange, I only have in my account currently about 30 bts. 

When I see the transactions made (as you can see in the files sent), I see that it has been sold in several automatic operations, approximately: 1226, 822, 190 and 6 at different bitusd / BTS rates. 

Could you help me recover my lost funds? In case you were not the one who can offer me that help, can you tell me who it is? What kind of failure has caused this problem? Please, I am saying that all funds in my account and not a negligible amount have disappeared, without a clear reflection, is a serious error of the system ?.

I need these funds quite urgently, I would appreciate all the help and information possible, sorry if it is not the appropriate place for it, but it is what is indicated when you click on the help button. 

Thank you very much for your help
 
[BitShares - Cuenta - clgc1972 (1).pdf](https://github.com/bitshares/bitshares-ui/files/2919220/BitShares.-.Cuenta.-.clgc1972.1.pdf)
[BitShares - Cuenta - clgc1972.pdf](https://github.com/bitshares/bitshares-ui/files/2919221/BitShares.-.Cuenta.-.clgc1972.pdf)

**Comment by sschiessl-bcp** [comment] 2019-03-05 13:55
Duplicate of #2496

**Closed by sschiessl-bcp** 2019-03-05 13:55 UTC
