### ISSUE TITLE
Layout issue in CN locale settings.

### ISSUE THREAD

**Issue by pluswave** [bitshares/bitshares-ui#621] opened 2017-10-20 10:48 UTC
see image below: 
<img width="1403" alt="2017-10-20 6 46 01" src="https://user-images.githubusercontent.com/5653443/31817560-2a798448-b55a-11e7-8f10-537b72e0a8d8.png">

**Comment by svk31** [comment] 2017-10-20 11:30
Duplicate of #607 and already fixed.

**Closed by svk31** 2017-10-20 11:30 UTC
Labels: duplicate
