### ISSUE TITLE
Canceling Order When All BTS Locked In The Order Is Not Using bitCNY Fee Pool Properly

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#1450] opened 2018-04-20 11:17 UTC
I have been having serious issues when I have all my BTS in a sell order and then I try to cancel it without having any available BTS to pay for the cancel fee.

Even though it says the fee is being paid in bitCNY and I DO have bitCNY it will not take the bitCNY to pay the fee. Something is wrong with the bitCNY fee pool. It tries to pay in some other asset that I do not have enough of to pay the fee from their fee pool, in my case "FORDCOM". Why would it go to FORDCOM instead of bitCNY when it says bitCNY in the Fee field and I have enough bitCNY?

If I do NOT have bitCNY NOR BTS available then I understand this. A solution would be to implement the BTS Preservation as discussed in issue #1412 which has become extremely urgent. I have even had to resort to sending BTS from another account to be able to cancel my order.

**Comment by abitmore** [comment] 2018-04-20 16:55
Where did you see "bitCNY" as fee for cancellation? There is no such a thing in UI. I guess
* it's either the market fee when your order is filled, or
* it's for creating a new order.

I think this is duplicate of #1117. @wmbutler ?

**Comment by wmbutler** [comment] 2018-04-20 17:25
I really don't know how to solve your problem @landry314. I think the solution to #1412 is not a very good one. Maybe you can help offer some input on that issue.

Regarding the display of bitCNY if/when the FORDCOM pool is empty, please post a screencast so a dev can see it in action and pick up this bug.

**Comment by abitmore** [comment] 2018-04-20 17:51
@wmbutler please read my comments above.

**Comment by landry314** [comment] 2018-04-20 18:33
yes, i have bought 1BTS at market to be able to pay cancellation fees... a few times.

if it happens again, yes, i will screenshot. i should have. i was rushing at the time to cancel my order. it tried to use FORDCOM to pay the cancellation fee, that i am sure of.

**Comment by abitmore** [comment] 2018-05-09 08:32
I think this is duplicate of #1117.

**Closed by abitmore** 2018-05-09 08:32 UTC
Labels: question
