### ISSUE TITLE
[1.5][happyconcepts] Notify user on Market asset with high fees

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1369] opened 2018-03-31 06:17 UTC
The Bitshares DEX is a place for free market and the possibility to create and trade anything that anyone can imagine.

This free place can sometimes also create opportunities for scammers to trick our users. Even if people shouldn't trade assets without first reading carefully what they are, we could help our users to highlight potential ill behaviour.

It's come to our attention that there are assets created with a high market fee. ~~market fee higher than 100%.~~ 

We do visualize the fee in the Buy table on the market page, but we could make it even more apparent that one asset has a higher fee than normal.

I'm not sure what levels we should work with, but we could do something like these.

- `0%` = White
- `<2%` = Green
- `<10%` = Yellow
- `>10%` = Red

**Comment by grctest** [comment] 2018-03-31 13:16
```
> 0 < 2 = White
>= 2 < 5 = Green
>=5 < 10 = Yellow
>=10 = Red
```

Sound better?

**Comment by happyconcepts** [comment] 2018-04-08 05:35
Walk me through the transaction? 

1. I want to buy a "fat-fee" coin spending 1,000 bitshares to do so...

2. The UI checks my balances and warns me if I don't have enough BTS for the transaction fee. This is to avoid the "could not broadcast transaction" error.

3. Assume I now buy the coin and it has an embedded fee of 150%.

4. What happens? Now that I spent 1,000 BTS... Are all of the coins I just bought now immediately returned to the issuer to satisfy the fee? 

Should some sane fee limit be imposed by the chain (not just the UI) when creating a token?

**Comment by wmbutler** [comment] 2018-04-08 18:35
I think the warning should appear here on the Market Fee line as a percentage:

- 2% high

I think any fees 2% or over should be considered high and we should state it. If we set 10% it will just encourage people to game the system at 9.99%. I'm also not a fan of having multiple levels. It's either a high trading fee or it's not and I think anyone would agree that when trading an asset, a 2% surcharge is high.

![screen shot 2018-04-08 at 1 29 14 pm](https://user-images.githubusercontent.com/1254810/38471019-ef193954-3b30-11e8-9f1b-b82c460a4ebe.png)

**Comment by abitmore** [comment] 2018-04-08 19:05
There is a "Market fee" label in the panel, we can add the percentage after it, e.g.
```
Market fee (2%):    0 OPEN.EOS
```

and use different colors e.g. green - yellow - red for low to high fee rates. Except this, do we have other methods to notify the user?

**Comment by wmbutler** [comment] 2018-04-08 19:24
I suggested adding the word "high" as well.

**Comment by happyconcepts** [comment] 2018-04-08 20:58
I think we leave it alone. We must not arbitrarily limit or label it. Calling it a "fee" is bad enough, actually, from this perspective.

Based on the info from @abitmore about the 100% maximum, the concept is safe. A user cannot potentially "spend" more than they think they are spending when they place an order.

If 150%, 200% eg more than the amount knowingly "spent" were possible then it would be a problem.

**Comment by wmbutler** [comment] 2018-04-10 00:39
As usual, we disagree. Adding clarity and a subtle warning is consumer friendly and does no harm.

**Comment by happyconcepts** [comment] 2018-04-12 01:30
The system was designed to handle many different types of coins. People do not label a $1,000 face value bond as "high-priced" when they compare it to a $50 stock. They call it a bond instead. 

You are making an inaccurate assumption to say that all coins are the same and must in all cases carry less than ___ % fee in order to avoid being labelled "high fee".

Also, it simply isn't the role of the front end dev team to be arbitrarily deciding how tokens are presented.

> and does no harm.

I disagree. And I lost 10 more minutes of my life replying to this only for you to ignore me, again @wmbutler. Shall I expect retribution?

**Comment by wmbutler** [comment] 2018-04-12 13:39
Nope. But you can't alter my opinion that a 2% fee for a one time transaction is close to usury. So, we can just let this die I suppose. Well done.

**Comment by abitmore** [comment] 2018-04-12 18:39
Just closed? IMHO it still makes sense to at least show the number.

**Comment by wmbutler** [comment] 2018-04-12 19:43
I agree @abitmore.

- [ ] Display % of transaction

**Comment by happyconcepts** [comment] 2018-04-14 01:05
I suggest a simple change, net coins is the best UX path here.

***Because also certain chain tokens like bitUSD now carry an embedded fee.***

If the expected net amount of coins from a successful transaction is clearly visible when the order is made, there is much less chance for surprised buyers.

Please include the net amount of coin the buyer will receive.

**Comment by abitmore** [comment] 2018-04-14 17:48
@happyconcepts good idea

**Comment by happyconcepts** [comment] 2018-04-18 01:25
What precision should this be? This is much longer than eight places:
![round-market-fee](https://user-images.githubusercontent.com/14145836/38906591-71c96dfa-426c-11e8-9f8c-22fb19cadf75.png)

**Comment by happyconcepts** [comment] 2018-04-22 02:58
> @wmbutler thanks for the discussion. I would like to claim this issue

Is this one not claimable? I could have done it this weekend...

**Comment by wmbutler** [comment] 2018-04-22 17:30
@happyconcepts I've assigned it to you, but agree on how this will be pursued before you begin work on it. My understanding is that we already show the market fee. The addition is to display a percentage of the overall transaction value to help people understand the magnitude of the transaction.

**Comment by happyconcepts** [comment] 2018-04-23 04:07
Ok, great. Let's establish a specification together:
1. UX ... where is the % displayed beyond being in the tooltip already. Also, where is net amount displayed.
2. Round down the amount by coin precision.
3. Display Net amount as estimated.
4. Display fee % prominently. 

I believe we have established that we shouldn't arbitrarily set percentage thresholds, so as not to limit current and future use cases beyond trading. 

Such as the use case where a high fee is purposefully set in order to discourage trading of the token.

**Comment by wmbutler** [comment] 2018-04-23 14:16
Either submit a visual or work with @ahdigital

**Comment by happyconcepts** [comment] 2018-04-27 21:41
Will post a screenshot this afternoon, added another row to display fee percent.

**Comment by wmbutler** [comment] 2018-04-28 16:06
I'm not sure you need another row, but awaiting your screenshot.

**Comment by happyconcepts** [comment] 2018-04-29 01:14
So here is what it looks like with a new row added. We are tight for space on that first column, so tight that the existing `Market Fee` display is already clipped when on a small screen.

![ux3](https://user-images.githubusercontent.com/14145836/39402284-ccc85a58-4b0f-11e8-9043-c2b8f659969f.png)

With the current UX layout for this buy/sell screen, neither `Market Fee Percent` nor `Market Fee %` will fit in the label div.

**Comment by wmbutler** [comment] 2018-04-29 18:02
I prefer the second option.

**Comment by happyconcepts** [comment] 2018-04-29 20:15
Great. Will you add 1 or 1.5 for the rounding bug too? I broke it out separately as #1469 and it needs some testing before PR.

**Comment by ahdigital** [comment] 2018-04-30 07:05
Just an idea - would moving the market fee value (0.1%) into a tooltip help with the spacing issue.

**Comment by abitmore** [comment] 2018-04-30 11:50
@ahdigital this issue is here since people didn't notice the `x%` market fee even when there is a `(?)` sign on UI already, so I think it's better to show it on the screen directly rather than to show in a tool tip.

**Comment by ahdigital** [comment] 2018-04-30 12:05
That'll teach me not to read the entire thread.. What about this to shorten the label:

![image](https://user-images.githubusercontent.com/3088454/39426252-0e236138-4c77-11e8-9f06-2a27b54b7879.png)

**Comment by happyconcepts** [comment] 2018-04-30 14:05
@ahdigital welcome your feedback. 

Both of your suggestions were actually attempted earlier.

But fee amounts are up to eight decimal places in length depending on the coin. 

Also, long asset names such as  CADASTRAL are problematic with that design.

Also, parentheses are used for negative amounts in finance.

If the market fee percentage needs to be made even more apparent to the first time buyer (I do not happen to think so) then I suggest making the market fee more apparent on the ASSET page instead of Order Entry (OE) and linking to that page easily from the OE box.

Myself, I am a trader. The OE box has already become cluttered enough that I do not look forward to ordering with it. I trade elsewhere now mostly, actually, for this reason.

**Comment by ahdigital** [comment] 2018-04-30 14:36
No no, it's fine and good information to know. I'm going to use it as a test against the exchange UI I'm working on in another task to ensure the work here is transferable.

**Comment by happyconcepts** [comment] 2018-05-01 18:54
> most users won't click to asset page so won't notice the fee rate.

@abitmore well actually all users won't click to the asset page as there's no link to it!

**Comment by startailcoon** [comment] 2018-05-01 19:33
@happyconcepts it's linked on the market header row, when you click on either asset pair name.

**Comment by happyconcepts** [comment] 2018-05-01 20:05
@startailcoon thank you for pointing that out. Those links seem inconsistent :(

**Closed** 2018-05-08 08:59 UTC
Labels: UX, feature
