### ISSUE TITLE
Created an Account Based Name via Wallet Mode

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#438] opened 2017-09-22 10:21 UTC
and it's completely bugging my client now. 

I can't deselct the account based name, even if I delete and re-add my wallet .bin.

edit: had to delete full cache (removing the account) for it to work again

**Comment by landry314** [comment] 2017-09-22 13:39
I have had to do a full clean install countless times due to the account management system being really buggy but some fixes have recently been implemented which might help:

https://github.com/bitshares/bitshares-ui/commit/d84096e81ad5ea96f65e36c003f9b76244333ed3

**Comment by svk31** [comment] 2017-09-22 15:41
If you run into issues like this the easiest way to fix it is to simply clear your localStorage. I suspect the key 'passwordAccount' is all you really need to delete. Perhaps we should remove account model account creation when you're already using a wallet, it probably causes confusion more than anything else.

**Comment by btsfav** [comment] 2017-09-22 18:33
@svk31 but then I won't be able to create accounts under my account. would take a LTM feature away

**Comment by landry314** [comment] 2017-09-22 18:45
You see the confusion with the word account? It is a mess. I am creating an issue all about the use of this word in the program.

Your "Wallet" can have as many accounts as you want to create. When you are using the "Wallet Model" then you create accounts in the ACCOUNT section (tab on the top) on the bottom in the box "CREATE A NEW ACCOUNT".

@svk31 is saying that once you have the Wallet Model chosen and you click in this box to create an account inside your wallet, that the choice for "Account Model" should not be an option.

I absolutely agree. There could be instead an option to switch to the Account Model (which needs to be renamed immediately).

**Comment by btsfav** [comment] 2017-09-23 09:29
@landry314 yeah, it's ridiculous.

but to come back to topic: as LTM you're allowed to create premium names, and I want to be able to.

Creating premium accounts, as in account model, for friends comes in very handy. they don't mind me knowing their first password and I get 80% of their fees as registrar. This must stay, there must be a way to make this work

**Comment by wmbutler** [comment] 2017-09-23 15:35
@svk31 I do like the idea of removing the account model once a user has chosen the wallet model. @btsfav your statement is incorrect. It's possible to create accounts without them being an account model. This terminology is terribly confusing.

**Comment by landry314** [comment] 2017-09-23 22:44
@btsfav, I had a friend do that for me. He created a premium name with his lifetime account then added keys I generated with the Paper Wallet then I deleted his keys, transferring the account to me, then I mde it a lifetime account and I started registering my own accounts and getting 80% back on all my fees.

The problem is that the faucet which registers your first account will not give you a premium name so in order to get one you would need to lifetime a non-premium name then use that to create a premium name which would not be a lifetime account. you would have to make two lifetime accounts if you wanted that to be your main account... it is too bad.

**Comment by kimchi-king** [comment] 2017-09-25 18:01
@landry314 "Your "Wallet" can have as many accounts as you want to create." Any more than 100 will break the API and make it impossible to deposit/withdraw any non-BTS token into that account. I learned this the hard way. Not trying to bring up my closed ticket. Just want to ensure that we aren't telling people misleading information.

**Comment by wmbutler** [comment] 2017-10-17 02:24
Status on this?

**Closed** 2018-01-15 02:44 UTC
Labels: question
