### ISSUE TITLE
After 1st sign-up you constantly see the "loading" animation

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#650] opened 2017-10-25 20:11 UTC
Usually a simple refresh does the trick, but I'm hearing this every now and then from new users. 

can you setup an auto-refresh?

**Comment by wmbutler** [comment] 2017-10-25 22:13
Probably a bad idea to do an auto-refresh. If you can't reproduce it consistently, we can't fix it. I'm guessing this has to do with latency and timeouts.

**Comment by wmbutler** [comment] 2017-10-28 18:34
Marking as a question until we can reproduce.

**Comment by svk31** [comment] 2017-10-30 11:27
It's an issue with the faucet that only occurs randomly, hard to fix without being able to reproduce. I've had it happen a few times myself too, but the account still got created and a refresh always fixed it.

**Comment by startailcoon** [comment] 2018-10-20 20:57
Closing this as nothing further has been reported since the fix supplied in nov last year.

**Closed by startailcoon** 2018-10-20 20:57 UTC
Labels: question
