### ISSUE TITLE
Explored account

### ISSUE THREAD

**Issue by kapeer42** [bitshares/bitshares-ui#2024] opened 2018-10-17 13:42 UTC
**Is your feature request related to a problem? Please describe.**
Currently the app does not fully makes the distinction between the currently explored account and the current user account.

**Describe the solution you'd like**
I'd like to see a change in the header from:
```
[BTS][dashboard][exchange][explore]                      [currentAccount][loginState][burgerMenu]
```
to:
```
[BTS][dashboard][exchange][explore]        [exploredAccount][userAccount][loginState][burgerMenu]
```
For a cloud account user the `userAccount` would always be his/her cloud account.
For a wallet account user the `userAccount` would be the currently selected account in the wallet.
The UI element showing the `exploredAccount` should be designed to clarify that the explored account is not your account.

Exploring to an account should set the current `exploredAccount` to that account.
If `exploredAccount  === userAccount`, the `exploredAccount` is not displayed in the header.

This should ease a lot of the proposals UX.
For example:
- Logging in with an account A then exploring to an account B and clicking on send on B's dashboard would auto-fill the send proposal with A as proposer and B as sender. The user would then just have to fill the destination and the amount. 

**Additional context**
This is a rough idea but I feel this would make the logic and UX of the app a lot better if thought through.

**Comment by startailcoon** [comment] 2018-10-20 20:01
I can agree with your statement @kapeer42 , that it can be confusing what account you're active as. The fact that the cloud accounts doesn't change when you browse another user makes it even more confusing if you switch account types.

Today the app "takes the role" of the selected account, but only when using in wallet mode. I find this behaviour confusing as you need to select your account in the header to switch back again.

We need to find a good practice for this, and I think @kapeer42 is on to something here.

cc @svk31 @wmbutler @sschiessl-bcp @gibbsfromncis

**Comment by gibbsfromncis** [comment] 2018-10-20 20:57
@startailcoon actually we have this feature I will work on - https://github.com/bitshares/bitshares-ui/issues/1089

**Comment by startailcoon** [comment] 2018-10-21 21:18
Nice, I didn't remember that issue when writing my reply here 👍 

Duplicate of #1089

**Closed** 2018-10-24 08:32 UTC
Labels: [0] Duplicate, [1b] User Story
