### ISSUE TITLE
[1.5] Web wallet is not connecting to Dallas Node

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#349] opened 2017-08-31 12:38 UTC
There is nothing obviously wrong with the Dallas Node because the Light Wallet connects to it just fine.

Screencast for demonstration. Might be good to hotfix this if we find a solution.

![settings](https://user-images.githubusercontent.com/1254810/29924310-30c2ae7e-8e22-11e7-8ebf-c6a6fd86bb52.gif)

**Comment by wmbutler** [comment] 2017-08-31 12:48
It appears that when the web wallet attempts to connect to the Dallas Server, we get this message and it skips to the next server.

```
Unable to connect to wss://dexnode.net/ws, skipping to next full node API server
e.logFailure @ app.js:35
o @ app.js:35
(anonymous) @ app.js:35
Promise rejected (async)
(anonymous) @ app.js:35
e.connectWithFallback @ app.js:35
(anonymous) @ app.js:33
Promise resolved (async)
oe @ app.js:33
i @ app.js:6
(anonymous) @ app.js:6
(anonymous) @ app.js:6
r @ app.js:6
d @ app.js:6
a @ app.js:6
r @ app.js:6
(anonymous) @ app.js:6
a @ app.js:6
i @ app.js:6
r @ app.js:6
(anonymous) @ app.js:6
r @ app.js:6
d @ app.js:6
M @ app.js:6
a @ app.js:6
n @ app.js:6
d @ app.js:6
componentWillMount @ app.js:6
performInitialMount @ app.js:35
mountComponent @ app.js:35
mountComponent @ app.js:13
performInitialMount @ app.js:35
mountComponent @ app.js:35
mountComponent @ app.js:13
performInitialMount @ app.js:35
mountComponent @ app.js:35
mountComponent @ app.js:13
o @ app.js:33
perform @ app.js:19
s @ app.js:33
perform @ app.js:19
batchedUpdates @ app.js:35
i @ app.js:13
_renderNewRootComponent @ app.js:33
_renderSubtreeIntoContainer @ app.js:33
render @ app.js:33
(anonymous) @ app.js:33
(anonymous) @ app.js:33
t @ app.js:1
(anonymous) @ app.js:35
t @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1

```

**Comment by wmbutler** [comment] 2017-08-31 12:49
I think this deserves a bounty because it's not a problem with @calvinfroedge recent code changes.

**Comment by svk31** [comment] 2017-08-31 12:49
I did make some changes to bitsharesjs-ws today, are you using the latest code?

Btw can't see the screencast due to it requiring flash...

**Comment by wmbutler** [comment] 2017-08-31 12:58
@svk31 I changed out the screencast

**Comment by svk31** [comment] 2017-08-31 13:11
This is a duplicate of https://github.com/bitshares/bitshares-ui/issues/304, the crypto api of that dallas node has something wrong with it.

bitsharesjs-ws now swallows the error, I'll make it so gets propagated properly. This is the actual error for the dallas node:

```
Error: Unable to connect to node: wss://dexnode.net/ws, error:{"code":1,"message":"Assert Exception: _crypto_api: ","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api.cpp","line":255,"method":"crypto","hostname":"","thread_name":"th_a","timestamp":"2017-08-31T13:09:31"},"format":"_crypto_api: ","data":{}},{"context":{"level":"warn","file":"websocket_api.cpp","line":122,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-08-31T13:09:31"},"format":"","data":{"call.method":"call","call.params":[1,"crypto",[]]}}]}}
```

**Closed by svk31** 2017-08-31 13:12 UTC
Labels: bug, high priority
