### ISSUE TITLE
[2.0.181212-rc1][1.5] Integration testing by toi16 - File Manager Issue loading bin file

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2282] opened 2018-12-07 15:42 UTC
**Describe the bug**
When restoring a key file from a backup the file manager does not load the bin file the first time you select it. You need to re-select the bin file a second time from the file manager before it is loaded into the login modal.

**To Reproduce**
1. Go to 'padlock'
2. Click on 'padlock' (opens login modal)
3. Select Login with 'Key file (local wallet)
4. Click on 'Restore key file..'
5. select bin file in file manager window.
6. Click 'Open'
7. ERROR: file manager window reloads again with no bin file selected.
8. select bin file in file manager window.
9. Click 'Open'
10. bin file is loaded into login modal.

**Expected behavior**
When selecting a bin file using the file manager window, the bin file should load into the login modal immediately after pressing 'Open' in the file manager window.

**Screenshots**
Screenshot just before 'Open' is pressed:

![bin1](https://user-images.githubusercontent.com/23018324/49656483-6173f480-fa35-11e8-8d17-cb8e2b97493d.PNG)

Screenshot AFTER 'Open' has been pressed. (File manager window briefly disappears and then re-appears with the below screen, you need to then re-select the file and press 'Open' again)

![bin2](https://user-images.githubusercontent.com/23018324/49656492-68026c00-fa35-11e8-868b-b7aad1e7a25f.PNG)

**Desktop (please complete the following information):**
 My OS:
Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
Chrome, Version 71.0.3578.80 (Official Build) (64-bit)

**Additional context**

**Comment by toi16** [comment] 2018-12-07 17:44
I have just tested this using the Firefox Browser and the key file loads correctly, so this appears to be specific to Chrome. 
Chrome did not show any console log errors.

**Comment by sschiessl-bcp** [comment] 2019-02-22 10:14
Duplicate of #2301

**Closed by sschiessl-bcp** 2019-02-22 10:14 UTC
Labels: [1b] User Story, [3] Bug, [4b] Normal Priority, [5b] Small, [6] Release Candidate, [7] Estimated
