### ISSUE TITLE
Cancel all orders with one click + confirmation click

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#619] opened 2017-10-20 07:27 UTC
Cancelling any more than two orders is a pain. Once you click the red cross, you can't click the next one before the confirmation bubble appears. That usually takes more than 3 seconds. If the user needs to free up funds from the limit orders, he should be able to do it painlessly.

**Here are some different approaches:**

- One click to free all [ASSET NAME] from limit orders. This would leave all other assets untouched
- One click to remove all orders from a specific market. This would remove orders from both sides.
- One click to remove all orders from all markets.

This feature won't change the first impression for new users, but it would make the life of power users easier.

**Comment by svk31** [comment] 2017-10-20 07:49
Closing as duplicate of #558

**Closed by svk31** 2017-10-20 07:49 UTC

**Comment by MarkoPaasila** [comment] 2017-10-20 08:02
Oh I'm sorry. I'd better search beforehand more carefully next time.
