### ISSUE TITLE
[2] Initial node connection is unpredictable and inconsistent

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#531] opened 2017-10-09 18:22 UTC
I believe we have a very fundamental problem in the code that handles choosing a node for the first time. It's not really an issue once a node has been selected so it's sort of been unnoticed and swept under the rug. Attached is a fairly long screencast demonstrating how the client will arbitrarily connect to sites that are not near to my client. There of course could be many causes including:

- Node query api is incorrectly reporting latencies
- Node selection api is not taking enough time to establish a connection or is not fulfilling some promise or callback

One thing that was striking while performing tests is that I only received a complete and proper connection when connected to the Dallas, TX node. I could theorize that this is because of low latency, but, oddly, it's possible for me to switch to a new node manually from the UI and use nodes with higher latency.

I believe a permanent fix is a two pronged approach of (a) ensuring we have an accurate reporting of latency and (b) carefully monitoring the socket connection process to observe areas where it is getting hung up.

This is a long screencast with about 7 attempts. The last few attempts all went to the Dallas Node and therefore worked properly.

![auto_node_select](https://user-images.githubusercontent.com/1254810/31352583-e2c59b90-acf4-11e7-8413-e402985ada70.gif)

**Comment by svk31** [comment] 2017-10-11 08:57
You certainly seem to have a dodgy internet connection, because in the first case all of the websocket connections fail. I see there's a missing catch and callback for that which I'll add.

**Comment by svk31** [comment] 2017-10-12 10:15
Closing this, will reopen if it keeps happening and someone can provide steps to reproduce.

**Closed by svk31** 2017-10-12 10:15 UTC
Labels: bug, high priority
