### ISSUE TITLE
Vesting Balances Claim from market_fee_sharing

### ISSUE THREAD

**Issue by tiago-dynx** [bitshares/bitshares-ui#2923] opened 2019-07-10 18:55 UTC
**Describe the bug**
Cannot claim vesting balances from market_fee_sharing

**To Reproduce**
1. Go to 'Top right menu button'
2. Click on 'Vesting Balances'
3. Click on claim on a Vesting balance with value below 1, like 0.00250 for example
4. The quantity will show as 0.0000000 on the popup modal
5. When confirm, shows execution error

**Expected behavior**
The user should be able to claim vesting balances

**Screenshots**
![image](https://user-images.githubusercontent.com/52141791/60996385-65aa1c80-a34c-11e9-8484-7a233b6bfe32.png)
![image](https://user-images.githubusercontent.com/52141791/60996422-79558300-a34c-11e9-9c28-2a6901ce10dc.png)
![image](https://user-images.githubusercontent.com/52141791/60996471-8ecaad00-a34c-11e9-91c8-9ae4fc92e427.png)

**Desktop (please complete the following information):**
 - OS: [Linux and Windows]
 - Browser [Chrome and FF]
 - Version [Latest]

**Comment by tiago-dynx** [comment] 2019-07-10 18:56
This was on testnet

**Comment by xiao93** [comment] 2019-07-11 16:27
+1 @abitmore

**Comment by abitmore** [comment] 2019-07-11 17:51
Duplicate of #2917.

**Closed by abitmore** 2019-07-11 17:51 UTC
Labels: [0] Duplicate
