### ISSUE TITLE
[6] Market order rounding - very confusing

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#314] opened 2017-08-23 16:36 UTC
![](https://i.imgur.com/Vv8HmqX.png)

so when you're trying to buy for last price (via clicking), the order is actually rounded up, ending up in a new buy order instead of an execution. 

super confusing

so either fix this and/or add a clickable

* last ask
* last bid

**Comment by wmbutler** [comment] 2017-08-23 16:42
Values should be the same in every screen.

**Comment by svk31** [comment] 2017-08-23 18:38
This is more complicated than it seems and a bit difficult to explain. The reason it happens is that BTS has a precision of 5, meaning 5 decimals maximum, as you see in the confirmation screen. Now, prices are defined **only** by the quantity of assets you are trying to sell and buy, they're not defined like we input them, and assets have max precisions.

If you want to buy 1 OBITS, you cannot do so using 7.03747402 BTS, because that is not a valid amount of BTS, meaning the order needs to get rounded up or down to the precision of BTS. In the case of buy orders, they need to be rounded up in order to match the ask.

The price you get from the lowest ask **is** a valid price for the the ratio of BTS to OBITS defined by that order, but most likely not for your arbitrary amount.

Limiting the amount of decimals in the price input is not a great solution imo, since any price can be valid, but the validity depends on the quantities of the assets being bought and sold in the order.

**Comment by wmbutler** [comment] 2017-08-24 00:08
I think this may need more discussion of @abitmore or @oxarbitrage or @xeroc. It's these types of issues that can cause trust issues to end users. In this case, we are asking for an order confirmation, but the confirmation screen does not match the order screen. I'll throw an hour on this if someone cares to claim to research and then we can increase the time as the fix reveals itself.

**Comment by recrypto** [comment] 2017-08-24 02:41
It would probably be advisable to add a notice on the confirmation dialog about the final price being rounded up or down with the 5 decimal precision so users are aware for the fact that BTS has that nature.

Example:
"*Final payment is rounded to a 5 decimal precision."

It will be intuitive for the user who is buying or selling that there exist a rounding with 5 decimal precision. :)

**Comment by oxarbitrage** [comment] 2017-08-24 12:02
i don't think there is much we can do from the bitshares-core as the price is calculated in the fly by the amounts as sigve described.
i think it will need to be rounded in the gui, before confirmation. **FINAL PRICE USED TO BUY: 7.03748**

**Comment by oxarbitrage** [comment] 2017-08-24 12:05
don't show 7.03747402 BTS or show it in smaller font. highlight the final price rounded, remain the long decimal if you want just as a proof but with less screen leadership than the final price.

**Comment by wmbutler** [comment] 2017-08-24 16:28
Can we have a js validator that rounds the value appropriately regardless of what the user enters?

**Comment by happyconcepts** [comment] 2017-08-28 04:28
Kraken just announced today: they are reducing the decimal precision for trading pairs. What if BTS were to do something similar? Dust could accrue to a house account and voted for what to do with it.

Those tiny cleanup prints are arguably noise instead of signal on the chart...I cannot think of another exchange where this happens.

**Comment by svk31** [comment] 2017-08-28 07:07
Yea I got that email too from Kraken. It's a decent idea and something I've already considered, but we can only prevent it on a GUI level, which means anyone using bots or trading through the CLI or other means will have an advantage over GUI users because they can use higher precision. If it could be enforced by the witness_node that would make it universal and more useful.

**Comment by abitmore** [comment] 2017-08-29 13:14
There are deeper issues. See https://github.com/bitshares/bitshares-core/issues/342

**Comment by wmbutler** [comment] 2017-08-31 21:18
I'm upping the bounty on this by an hour.

**Comment by svk31** [comment] 2017-09-05 08:31
I'm tempted to say "this is a feature, not a bug", since it's only confusing if you don't understand how Bitshares prices work in the first place. There really is nothing to fix here, since the final price depends on the amounts you use. 

Taking the initial price of 7.03747402 BTS/OBITS (which is the lowest ask):
* If you want to buy 1 OBITS you will need to sell 7.03748 BTS, making the price __7.03748 BTS/OBITS__
* If you want to buy 10 OBITS you will need to sell 70.37475 BTS, making the price __7.037475 BTS/OBITS__
* If you want to buy 100 OBITS you will need to sell 703.74741 BTS, making the price __7.0374741 BTS/OBITS__
* If you want to buy 1000 OBITS, you will need to sell 7037.47402, making the final price exactly __7.03747402 BTS/OBITS__

As you can see, there is no "correct price", it depends on the quantities you're buying and selling! And the higher your amounts are, the more exact your price will be.

In my opinion at best we could add a * and hover tooltip explaining that the price you see in the input field may not be the final price on the blockchain, and that it depends on the amounts purchased as explained above.

**Comment by wmbutler** [comment] 2017-09-08 04:26
Why can't we perform this calculation change in the input field based upon the quantities entered below it? We do it on the confirmation screen.

**Comment by svk31** [comment] 2017-09-11 18:54
I'll make it so the displayed price updates based on new amounts being entered so that it should always match the confirmation window price.

**Comment by wmbutler** [comment] 2017-09-11 18:55
Perfect. I think this is better behavior.

**Closed** 2017-09-13 07:16 UTC
Labels: bug

**Comment by wmbutler** [comment] 2017-09-13 16:16
So happy this one is behind us!!
