### ISSUE TITLE
Invoice.jsx needs update

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#121] opened 2017-04-18 07:44 UTC
The invoice.jsx needs updating.

* the "pay" button misses a label
* the redirect to the callback as offer in the query string is not taken into account

Example:
    https://wallet.bitshares.eu/invoice/JLNHPVjqNdeaeXvP3A42vby858DvomCLVoMwbHNhrUFDvMBUHYabpXeZKCEhvKwKpvhSY9k3zvEJsmgqHywd8WVdj9bKyYrkKsA179o7mvHofS39rMYjNeCEWyrgqCDZcM9ZJuVk2S482rUa3tCFkTz3c9cBuuCVZVNYsaskQeLsdRntW2ZaejXrjshFKKqmTzTPotuXzAnEUSXuQ3RJCXet74PDWfNd44ynus4bDWtRTdXa2Vx8iUwVPzWhYaEKYxcsaZtMSSbfxfKL6yyvZU3CfC2sChxuLZhojgaUswpMkpinV6xDpwAicz5aHnpN4V4u7c4YQj9ZPVf5

See also: http://docs.bitshares.org/integration/merchants/merchant-protocol.html

**Comment by ProZachJ** [comment] 2017-06-22 23:50
@xeroc Couple things.

1. The documentation shows the url being /#/invoice, but I've confirmed the URL provided above /invoice is the correct URL. I'm using the python script in the docs to generate the invoices but had to modify it just a bit to get a working invoice URL
```python
import json
import lzma
from graphenebase.base58 import base58encode, base58decode
from binascii import hexlify, unhexlify

invoice = {
    "to": "faucet",
        "to_label": "BitShares Europre",
        "currency": "TEST",
        "memo": "Invoice #1234",
        "line_items": [
                {"label": "Something to Buy", "quantity": 1, "price": ".0001"},
                {"label": "10 things to Buy", "quantity": 10, "price": ".0001"}
        ],
        "note": "Payment for reading awesome documentation",
    "callback": "https://localhost/complete"
}

compressed = lzma.compress(bytes(json.dumps(invoice), 'utf-8'), format=lzma.FORMAT_ALONE)
b58 = base58encode(hexlify(compressed).decode('utf-8'))
url = "http://localhost:8080/invoice/%s" % b58
```
2. What do you mean by "the redirect to the callback as offer in the query string is not taken into account"?  I'm not seeing any redirection occur at all on my local client connected to the testnet. Any idea what I'm missing?

**Comment by ProZachJ** [comment] 2017-06-23 00:31
Doing a bit of debugging it looks like the then() method here: https://github.com/bitshares/bitshares-ui/blob/bitshares/web/app/components/Transfer/Invoice.jsx#L102 is not being called. That would explain the callback not happening.

Reading backwards to see what is going on.

**Comment by ProZachJ** [comment] 2017-06-23 16:54
Still haven't figured out the issue with `then()` not being called after transfer, but I've managed to fix the display issue with the send button.
![screen shot 2017-06-23 at 11 53 22 am](https://user-images.githubusercontent.com/2414138/27492111-9cef3232-580a-11e7-96cd-1dd90e3f6bd0.png)

**Comment by ProZachJ** [comment] 2017-06-23 18:23
I don't know if it is desired but I've changed the routing to pass the invoice data in the hash per the documentation.

**Comment by ProZachJ** [comment] 2017-06-23 20:02
Tracing back why the callback is not being respected...

`onBroadcastAndConfirm` does not appear to ever get called.
https://github.com/bitshares/bitshares-ui/blob/bitshares/web/app/components/Transfer/Invoice.jsx#L74

Similarly in Transfer.jsx  `onTrxIncluded` doesn't appear to ever get called either.
https://github.com/bitshares/bitshares-ui/blob/bitshares/web/app/components/Transfer/Transfer.jsx#L128

I'm assuming that `onPayClick` is calling `TransactionConfirmationStore.listen` to register `onBroadcastAndConfirm` as a callback, but I'm unclear on where to find the implementation of `TransactionConfirmationStore.listen` I looked here: 

https://github.com/bitshares/bitshares-ui/blob/bitshares/web/app/stores/TransactionConfirmStore.js

and here:

https://github.com/bitshares/bitshares-ui/blob/bitshares/web/app/actions/TransactionConfirmActions.js

My best guess is the the `listen` method comes via reflection from bitsharesjs-ws?? Anyone know where I can peek into what it is supposed to be doing?

**Comment by ProZachJ** [comment] 2017-06-23 21:26
Ok this is strange behavior, if you visit the invoice link and pay, the first time the transaction is confirmed nothing happens. No redirect, none of the confirmation callbacks get called. However, if you wait till the transaction completes and then pay a second time all of the callbacks fire and the user is redirected. I'm thinking there must be some state issue going on.

**Comment by svk31** [comment] 2017-06-24 05:32
The reason this component is outdated is that it's never really been included and maintained. It was developed for a bank demo in the early days of BTS 2 but hasn't really been touched since then.

**Comment by xeroc** [comment] 2017-08-30 11:57
Can we have a refactoring of this Invoice page in the upcoming spring, please?

**Comment by wmbutler** [comment] 2017-08-30 14:04
I'd be happy to take this on. I suppose we could use this mechanism to send the bitshares-ui invoice once it's working properly.

**Comment by Gil707** [comment] 2017-09-08 09:02
I make some fixes in this and add some functionality (default currency getting from invoice and fee asset changing) but have some problem, don't understand how correctly take fee for this opertaion (and convert it if need from BTS), there are the same functions in Transfer, but when do the same, I can not get the correct value anyway...
Here is my var - https://github.com/Gil707/GuronDEX-ui/commit/fd5c55ea5eb220eb238d9a2a222c52adcd5c9ccb

**Comment by clockworkgr** [comment] 2019-02-13 08:30
Are we going to re-add this functionality? Sounds like something for the spotlight @sschiessl-bcp 

If not, let's close the issue

**Comment by sschiessl-bcp** [comment] 2019-02-13 08:32
I didn't even know that exists xD

Yes, that would be an amazing spotlight!

**Comment by clockworkgr** [comment] 2019-02-13 21:45
@sschiessl-bcp Feature was removed in https://github.com/bitshares/bitshares-ui/pull/2053

Duplicate request at #2244

**Closed by clockworkgr** 2019-02-13 21:45 UTC
Labels: [3] Enhancement
