### ISSUE TITLE
[4] Sell Order Does not Show on the GUI

### ISSUE THREAD

**Issue by SahkanDesertHawk** [bitshares/bitshares-ui#146] opened 2017-05-16 16:37 UTC
In  BLOCK #16539841there is 2MLN BTS/BTC sale that does not sow on the orders book, and does not show under 'my open orders' on the that page.

**Comment by wmbutler** [comment] 2017-07-21 19:57
Please provide additional evidence. I'll reopen when you do.

**Comment by SahkanDesertHawk** [comment] 2017-08-03 17:56
This is easy to check you can put a high price order like 200BTS for 1BTC each and it will not show on the order book on the main page. It shows on the ACCOUNT, OPEN ORDERS list.

**Comment by wmbutler** [comment] 2017-08-03 20:48
This sounds to me like it's a lazyload issue? I'll see if I can reproduce and post some images.

**Comment by calvinfroedge** [comment] 2017-08-15 19:09
@wmbutler Possible to have more exact reproduction steps here?

**Comment by wmbutler** [comment] 2017-08-15 19:13
@SahkanDesertHawk moving this to question and taking out of the current Sprint until you can post screenshots fully reproducing this issue.

**Comment by SahkanDesertHawk** [comment] 2017-08-15 22:05
![ppy trade screen](https://user-images.githubusercontent.com/28378150/29338559-755d3bbc-81b1-11e7-8942-2e64015cc2c6.png)
I am running Linux Light Client v.170522. There are 3 trades waiting to execute on the main trade screen.
But I really have 4 Open orders:
![open orders](https://user-images.githubusercontent.com/28378150/29338650-dec9fe00-81b1-11e7-9073-308ce74fdb8a.png)

That order of 25/PPY is not reflected on the trade screen.

**Comment by wmbutler** [comment] 2017-08-16 13:15
Trying to understand the issue still. I see prices and qty that don't correspond in any meaningful way. Can you clarify?

**Comment by svk31** [comment] 2017-08-16 13:31
Your orders' prices are far too low to be visible in your screenshot, you need to scroll down the Buy Orders list:

![image](https://user-images.githubusercontent.com/6890015/29365602-e0b3915e-8297-11e7-91f9-e5b74394047c.png)

**Comment by svk31** [comment] 2017-08-16 13:33
The original issue is probably just from filtering out of orders with extreme price values, prices that are too far removed from the current market prices. They're filtered out for display purposes since prices with say 15 digits completely mess up the tables.

**Comment by wmbutler** [comment] 2017-08-16 13:40
What if we removed the total bts column (turned this value into a hover tooltip instead). Would this free up room to display the entire order book? This is a recurring theme and I'm not sure how else to get around it.

**Comment by svk31** [comment] 2017-08-16 13:44
No the total is very useful imo, much more so than showing irrelevant orders.

**Comment by wmbutler** [comment] 2017-08-16 13:46
"irrelevant" is subjective. Ultimately, we can't censor data. Need to be creative about how to show the full picture.

**Comment by SahkanDesertHawk** [comment] 2017-08-17 00:08
My order of 25per sometimes shows up and sometimes goes away. We should be able to show the most accurate picture of the order book. 25/PPY is not 15 digits. I tested it with 1MLN BTS, and once the order is dropped from the open orders screen on the right, the SELL ORDERS total gets adjusted by the amount and it also gets dropped from the Show all asks, so no I cannot scroll down the orders and see it.

**Comment by wmbutler** [comment] 2017-08-17 15:09
@SahkanDesertHawk a screenshot would help this.

**Closed** 2017-09-12 02:21 UTC
Labels: question

**Comment by landry314** [comment] 2017-09-12 19:58
I think this might be related to issue #393.

**Comment by SahkanDesertHawk** [comment] 2017-09-13 04:20
I have included the screenshots above. The bottom line on this is that the order book does not show a full picture even if the orders are within reasonable price range.
