### ISSUE TITLE
Second Order Placed Over a Blue Open Order In Order Book Takes Away Blue Color

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#1445] opened 2018-04-19 22:03 UTC
If you have an open order which shows up as blue in the order book and then another order from someone else is placed at the exact same price then the blue color disappears and the user only sees the cumulative price of both orders in the normal color.

This can be reproduced if you have two accounts. Place an order with one then another order with the other account at the same price.

**Comment by landry314** [comment] 2018-04-19 22:05
This is related to the initial issue #618.

**Comment by startailcoon** [comment] 2018-04-22 20:25
I can't reproduce this.

I placed one buy order of 1 open.USD with two different accounts. Both now view the order line of 2 open.USD for 0.8 BTS as blue.

![image](https://user-images.githubusercontent.com/12114550/39099475-0170f640-467c-11e8-82fc-7c20f8a7b6a5.png)

**Comment by startailcoon** [comment] 2018-04-26 19:02
@landry314 I can't do anything more on this unless I can get some details about your issue and why you have something other than what I have when I test this.

**Comment by clockworkgr** [comment] 2019-02-08 09:29
Can't reproduce & No further OP response. Closing

**Closed by clockworkgr** 2019-02-08 09:29 UTC
Labels: question
