### ISSUE TITLE
Explorer page is slow loading

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#1459] opened 2018-04-22 22:25 UTC
This is on a 10Mb/s connection; sneer if you want to but this isn't particularly slow for wifi here in the U.S.

Is the pageload slow due to the large number of coins being fetched? I want to search but I have to wait for all the coins a-z are belong to my browser.

**Comment by gibbsfromncis** [comment] 2018-04-23 01:39
@happyconcepts it's duplicate of #1435

**Closed** 2018-04-23 01:55 UTC
Labels: duplicate
