### ISSUE TITLE
"Show brainkey" button doesn't work 

### ISSUE THREAD

**Issue by react-cat** [bitshares/bitshares-ui#2330] opened 2018-12-13 14:08 UTC
1. Go to Settings page.
2. Go to backup tab. 
3. Select "Create brainkey backup".
4. Enter password.
5. Click "show brainkey" button. 
6. nothing happens.

![bitshares 2 0 181121 rc1](https://user-images.githubusercontent.com/43940398/49897354-9382bd80-fe5e-11e8-98b7-4f244560e992.png)

After my code review, I found out that the button doesn't submit the form cause one button parameter is missed. 

Estimated time: 15 minutes

**Comment by startailcoon** [comment] 2018-12-13 18:12
This worked for me in the current staging, 181212-RC1, that's strange.
Please submit your findings on this.

**Comment by clockworkgr** [comment] 2019-02-13 08:18
@react-cat Does this issue persist?

If noone can confirm/duplicate this we should close it.

**Comment by startailcoon** [comment] 2019-02-15 22:37
Closed due to inactivity from submitter and can't be reproduced

**Closed** 2019-02-15 22:37 UTC
Labels: [0] Awaiting User Feedback, [6] Release Candidate
