### ISSUE TITLE
[6] Design a new notification system

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#463] opened 2017-09-27 10:23 UTC
Steps to Reproduce:

1) Make sure you have more than one account "starred" so they are in the top pulldown
2) Make sure you have very recent activity in the current active account
3) Switch to another active account
4) Switch back to the original active account

You should see a notification pop up for the last recent activity on the account you switch to.

5) Switch back and forth again

You will keep seeing that notification pop up every time.

When a notification is dismissed it should never come back.

In the code there is something pulling up the last recent activity which simply should not be there.

I am not sure if the kind of activity or how old it is matters to reproduce but it does not always happen. For me, it was a "bought 14,842.77 BTS at 0.515 bitCNY/BTS". More testing might be needed.

**Comment by wmbutler** [comment] 2017-09-28 13:32
Agreed that once an announcement has been presented, it shouldn't be resent everytime a user switches back to the account.

**Comment by landry314** [comment] 2017-10-01 11:58
This is hardly a feature request. This is a bug. It is not suppose to pull up the last recent notification informing you that a trade that happened 5 minutes ago just happened again... and again... and again... if you are switching active accounts a lot. It is disconcerting.

**Comment by wmbutler** [comment] 2017-10-01 21:44
You have way too much time on your hands to quibble about categorization. It's not a bug if it's working as originally intended. And it is working as originally intended.

**Comment by landry314** [comment] 2017-10-02 02:49
Just trying to help, Bill.

**Comment by wmbutler** [comment] 2017-10-11 06:10
Notifications block various controls and are redundant when switching accounts. Design a new way to view notifications.

**Comment by startailcoon** [comment] 2017-11-05 00:23
Can we replace the current notifications system with #686 perhaps?
I think any new notifications system should use browser/system notifications.

**Comment by wmbutler** [comment] 2017-11-07 14:20
Some will choose not to enable browser notifications. Our notifications need to be self-contained in those cases.

That being said, notifications should be visible from anywhere in the application in a consistent location, but they should not obscure any part of the app during display. This presents a design problem because we are forced to reserve space for something that is temporal.

I've found that the least bad option is to reserve a very small horizontal band at the top of the application. Benefits:

- Translates well to all sized devices
- Is very noticeable to the end user
- Takes up space, but the user tends to get used to the slightly larger gap at the top
- Accommodates a **lot** of text for those larger messaages
- Can incorporate different colors for say error - red, warning - yellow, info - green

![screen shot 2017-11-07 at 8 14 20 am](https://user-images.githubusercontent.com/1254810/32498164-7f309204-c394-11e7-9b8b-0d0fca7f0e92.png)

**Comment by svk31** [comment] 2017-11-16 12:22
I don't like losing even more vertical space, and frankly I don't see why we should even replace the current notification system. The current one works on mobile and desktop, this new one will be bad for mobile especially but also for laptops with low vertical resolution.

The issue in the OP is a fairly simple one to fix, it's simply because we don't store any state keeping track of what the last operation notification was for each account. Adding that would fix the original issue..

**Comment by wmbutler** [comment] 2017-11-17 02:26
I don't like the current notification system because it:

- Blocks areas of the screen while it's up
- Stays on for a predefined amount of time disallowing other user actions
- Has no color component to help the user understand whether it's informational or an error

**Comment by landry314** [comment] 2017-11-18 05:17
And it pulls up the last activity for that account when switching to an account, no matter how long ago it occurred... which is a bug.

**Comment by svk31** [comment] 2017-11-18 11:26
> I don't like the current notification system because it:
>
> - Blocks areas of the screen while it's up

This can probably be worked around
> - Stays on for a predefined amount of time disallowing other user actions

There's a default timeout and a custom one, so you can set a specific timeout for different notifications
> - Has no color component to help the user understand whether it's informational or an error

This is not true, the current notifications have a color component.

This is the notification library that's currently being used: https://github.com/igorprado/react-notification-system

Building something to replace it will be timeconsuming and in my opinion completely unnecessary.

> And it pulls up the last activity for that account when switching to an account, no matter how long ago it occurred... which is a bug.

I addressed this in my previous comment, it's simply a matter of adding localstorage state to track this, easy fix.

**Comment by wmbutler** [comment] 2017-11-26 18:01
If you can work around item 1, I'd be fine with that. My biggest issue with the notification right now is that it has to be dismissed before I can do anything else.

**Comment by gibbsfromncis** [comment] 2018-02-15 13:29
@wmbutler Lets do this big part step by step. I can prepare MVP of this feature and start to work if you agree.

**Comment by gibbsfromncis** [comment] 2018-02-15 14:17
First of all we should prepare the list of events we should notify user. We can start from our main operations:
- Fill order
- Transfer
- Price Alarm  (https://github.com/bitshares/bitshares-ui/issues/422)
(if you know more important operations let me know)

For me MVP looks like this:

- [ ] Add page where all notifications will be listed (on future we can add icon on header and dropdown but lets start without complexity)
- [ ] User should be able to "mark notification as read"
- [ ] Dismiss this kind of notifications on future. 
- [ ] Settings -> Notifications where user be able to enable/disable notifications types manually

It would be only Front-end Notification System so we can't notify users throw email about something. I'll track last operation ID on browser storage. And when user come back and fetch new operations I'll define new operations and add notifications about them. 

On future we can add complex features like this:
- Enable notifications only when user offline (for MVP it will works only on this way. But on future users be able to see notifications even he is online and on app)
- Dismiss specific kind of notifications with specific params (like disable notifications for `FILL ORDER` of BTS/bitUSD only, or disable notifications of `TRANSFER` from specific user only)

**Comment by wmbutler** [comment] 2018-02-17 17:06
I'm closing this since we have a start for Chrome notifications now. Please re-open in a different issue if there are some continued features.

**Closed by wmbutler** 2018-02-17 17:06 UTC
Labels: feature, low priority

**Comment by gibbsfromncis** [comment] 2018-02-17 18:05
@wmbutler Actually I've deployed Notifications for browsers. But for now we don't have any tab or place where we can see notifications which maybe interesting for users. In case of browser notifications user receive the message only if he have wallet opened. On another way he won't see any notification. Please read my (if you didn't) proposal - https://github.com/bitshares/bitshares-ui/issues/463#issuecomment-365939789. and just assign me to work on it.

**Comment by wmbutler** [comment] 2018-02-21 23:03
I don't think we need notification history. We already have activity logs for that.
