### ISSUE TITLE
Error cross-env: not found and npm ERR! code 128 and a lot error 

### ISSUE THREAD

**Issue by heyasjack** [bitshares/bitshares-ui#2739] opened 2019-06-02 07:52 UTC
Now using node v9.11.2 (npm v5.6.0)

> cross-env NODE_ENV=development node server.js

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! BitShares2-light@3.1.190604-rc1 start: `cross-env NODE_ENV=development node server.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the BitShares2-light@3.1.190604-rc1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-02T07_49_40_157Z-debug.log

bitshares-ui# npm install
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/bitshares/alt.git /root/.npm/_cacache/tmp/git-clone-49f65053
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-49f65053': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-02T08_05_41_637Z-debug.log

**Comment by heyasjack** [comment] 2019-06-02 08:09
I think maybe it was something wrong in installing nvm node and npm.
How can I uninstall all the nvm node and npm things?

**Comment by sschiessl-bcp** [comment] 2019-06-03 20:50
Duplicate of #2713

**Closed by sschiessl-bcp** 2019-06-03 20:50 UTC
