### ISSUE TITLE
[.25] The new chinese WP is not categorized properly right now

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#725] opened 2017-11-10 16:13 UTC
It's marked as active even though it has not yet received the required number of votes. Your logic apparently marks is as active even though it doesn't have enough votes to get it paid. Active Proposals from the standpoint of the UI must be:

- Within the current time window
- Received enough votes to be paid

**Comment by xeroc** [comment] 2017-11-10 16:16
Could be it's getting confused because of the refund100k worker (instead of the refund400k worker)

**Comment by wmbutler** [comment] 2017-11-11 16:13
@svk31 keep in mind that this was the case for the WP starting on 9 Nov. It had not received the required number of votes, but it was currently Nov 10 and it was on the active tab.

**Comment by svk31** [comment] 2017-11-13 10:04
Unable to reproduce, please take a screenshot next time. Was it below the refund400k worker?

**Comment by wmbutler** [comment] 2017-11-15 15:30
It wasn't below the refund worker. It:

- Did not have the number of required votes to be active
- Was scheduled to begin 11/9 and the current date was 11/10

**Comment by svk31** [comment] 2017-11-15 18:30
Most likely caused by you having an old budget object temporarily, as the GUI will need a second or so to fetch the most recent budget object. Old budget objects had a higher budget for workers which means you'll temporarily see workers below the refund400k worker as active. Closing as a non-issue.

**Closed by svk31** 2017-11-15 18:30 UTC
Labels: bug
