### ISSUE TITLE
[.25] Theme Midnight (OL Dark) needs some care

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#808] opened 2017-12-06 18:03 UTC
Most pages are not real midnight bg, but borrow from the current "dark theme".

this needs some work please

Good:

![](https://i.imgur.com/yLlfmgJ.png)

Bad Deposit/WD (of many):

![](https://i.imgur.com/ZE23YWu.png)

**Comment by wmbutler** [comment] 2017-12-06 22:55
This is not a problem on Chrome for Mac. Please state your browser and OS.

**Comment by btsfav** [comment] 2017-12-07 06:10
Windows 7, light client

**Comment by svk31** [comment] 2017-12-11 18:35
Is the right side gap the issue? If so I already fixed it. Deposit/Withdraw are both active because they have the same path for now, will change once the modals are ready.

**Comment by svk31** [comment] 2017-12-13 11:45
Closing since I have no idea what the issue is.

**Closed by svk31** 2017-12-13 11:45 UTC
Labels: feature

**Comment by btsfav** [comment] 2017-12-19 15:37
@svk31 the different shades of black is the issue
