### ISSUE TITLE
Margin Positions problems (v190410)

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-ui#2627] opened 2019-04-18 19:56 UTC
1. Tab "Margin Positions" on AssetInfo screen not show these positions.
2. In header not shown collateral ratio for my low-collateralized open margin position, feed price and global setlement. These values shown only for blackswaned assets with feed price. 

![image](https://user-images.githubusercontent.com/6587277/56387265-8a4e9680-622c-11e9-9083-3e6eda7a0ba9.png)

Version: Desktop 190410 
OS: Win10 1903 x64

**Comment by clockworkgr** [comment] 2019-04-18 21:28
Duplicate of #2625

**Closed by clockworkgr** 2019-04-18 21:28 UTC
Labels: [0] Duplicate
