### ISSUE TITLE
Market ticker is not updating call limit price fast enough

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#897] opened 2017-12-22 07:50 UTC
Specifically, when least collateralized margin position get called and successfully executed or changed, the ticker should update immediately to next call order's call limit, Currently it stays at old value for quite a while.

**Comment by wmbutler** [comment] 2017-12-24 01:31
Please post a licecap to demonstrate.

**Comment by HarukaMa** [comment] 2017-12-24 18:04
it could be difficult to reproduce on mainnet as there would need to have margin call events. 

Will try on testnet when I have time.


(is it really needed?)

**Comment by wmbutler** [comment] 2017-12-24 19:16
It's hard for us to resolve if we cannot reproduce.

**Comment by HarukaMa** [comment] 2017-12-26 13:48
![untitled](https://user-images.githubusercontent.com/861659/34357902-504a9c8e-ea8e-11e7-9479-e16f1af0c237.gif)

Finally got the chance to record this. It's fairly lengthy as I cannot predict the market.

Notice that on 0:24, the least collateralized position is being executed but the call limit ticker on the top is still at 3.914812 which is clearly wrong as the highest bid is already below that and the margin called orders are not executed further. It's only after refreshing the market tab on 0:40 that the call limit ticker get updated correctly.

**Comment by wmbutler** [comment] 2018-04-01 18:18
Closing this. It has had no takers for 4 months.

**Comment by startailcoon** [comment] 2018-06-23 07:22
Reopened as this may not be that hard to fix. All components should view the same amount when the backend is queried.

• [ ] investigate why header isn't aligned with the rest of the UI on call prices.

**Comment by startailcoon** [comment] 2018-06-26 09:43
I've tried to observe this behaviour now and can only come to the conclusion that this is no longer an issue. The header is updated according to the order table.

## Screen 1
Here we have the same price in header as in the order stock. The minature orders that is in blue are dust order and probably has a bit different value due to this.

![skarmklipp-1](https://user-images.githubusercontent.com/12114550/41903357-f5e960a4-7935-11e8-91e0-fa834b405b45.PNG)

## Screen 2
Here we have a larger order, both aligned with the current call price.

![skarmklipp-2](https://user-images.githubusercontent.com/12114550/41903380-045e3cea-7936-11e8-9936-21bee1bd3ad4.PNG)


The call price is adjusted acording to feed price, and does this correctly according to what I can see.

**Comment by startailcoon** [comment] 2018-06-26 09:45
@HarukaMa please notify me if you have further data in this issue that you can provide if you still think this is an issue.

**Comment by abitmore** [comment] 2018-06-26 15:25
@startailcoon about the strange price probably caused by dust, please:
* find if the result has a "fill_price" field, it there is one, use it; otherwise (for old API nodes), calculate price by amounts.

**Comment by startailcoon** [comment] 2018-06-27 04:57
@abitmore sounds good to be able to solve the dust orders, but that's not related to the topic, is it?
I will definetly take a look at it though.

**Comment by wmbutler** [comment] 2018-06-30 14:43
@startailcoon if this issue is fixed, please close and open a dust orders issue.

**Comment by startailcoon** [comment] 2018-06-30 15:31
Closing as no additional feedback has been submitted.

**Closed** 2018-06-30 15:31 UTC
Labels: invalid
