### ISSUE TITLE
New Entries Disapear on Permissions and Voting tabs

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#142] opened 2017-05-15 19:35 UTC
After adding a new key before you have time to press Publish Changes, the screen automatically refreshes and removes everything I've added back to the original state.  The same thing happens on the voting screen when adding new witnesses or committee before publishing.

Wait long enough and it will revert to the original state. 

bitshares. org/wallet bitshares.170508   and Lightwallet bitshares.170418
Chrome/Firefox/LightWallet(windows64)

**Comment by svk31** [comment] 2017-05-22 11:14
Unable to reproduce, anyone else seeing this?

**Comment by wmbutler** [comment] 2017-05-31 17:04
I haven't seen this happen.

**Comment by wmbutler** [comment] 2017-07-21 19:56
Closing due to inadequate evidence of issue.

**Closed by wmbutler** 2017-07-21 19:56 UTC
Labels: invalid
