### ISSUE TITLE
Provide "Loading..." feedback until UI is actually ready

### ISSUE THREAD

**Issue by mattbeckman** [bitshares/bitshares-ui#1074] opened 2018-01-28 07:18 UTC
"Loading..." appears for a moment, disappears to a blank (white or gray) backdrop, and stays like that until the API node connection loads and the UI is fully drawn. I can recreate all the time via Cmd+R.

I think we should have "Loading..." (or some helpful/optimistic variant like "Connecting to the BitShares network...") stay on screen until everything is... in fact... loaded. A modal with transparency might be interesting, but we don't need to get super fancy.

**Comment by ihorml** [comment] 2018-01-28 08:39
+1
I'm used to if screen is dark - something loading. But it makes really confusing especially when you start to use bitshares.

**Comment by wmbutler** [comment] 2018-01-28 19:26
Need some UX on this one.

**Comment by sschiessl-bcp** [comment] 2018-04-03 05:21
Can also fix #1353

I'd like to pick this up if you deem it worthwile @wmbutler .

My suggestion: 
Display initial loading screen until its actually ready, and then a loading overlay for the target page until connection is established / background work is done. I could see something like ConnectionActions that centralize the logic and displays connection information via a LoadingIndicator overlay that is implemented within the connection status display in the footer.

**Comment by clockworkgr** [comment] 2018-04-03 08:58
Not sure how much work it would involve, but possibly implement a "Status" mechanism (similar to a logging engine) where a singleton-type status message would be updated when certain promises are created and displayed whenever the loading (or 3 dot) modal is visible? 

So you get "Loading" along with "Connecting to node xxx" -> "Getting account data" -> "Subscribing to markets" -> "Preparing interface" as various actions are initiated and completed.

**Comment by svk31** [comment] 2018-04-03 10:32
Loading appears until the React app itself is loaded, which is the time it takes to load app.js and then initialize the app. That means there's no way to remove it with anything related to the connection status or anything at all that's part of the GUI.

It's a simple CSS loading indicator included directly in index.html here: https://github.com/bitshares/bitshares-ui/blob/staging/app/assets/index.html#L16

It could be replaced with a different looking loading indicator and a different text, but that's about it. There's also no way to load localized text there.

**Comment by clockworkgr** [comment] 2018-04-03 10:38
Ok. I was not referring simply to the Loading indicator but also the 3 dots and the black screen between loading disappearing and everything fully ready for use. i.e. have a Loading indicator post-react loading until everything is set-up...

In the example above it could be Loading - Initialising App as a first step prior to the localised status changes mentioned above.

Just throwing some ideas out there

**Comment by svk31** [comment] 2018-04-03 11:02
Just to be clear I was referring to the "Loading..." that shows up first thing when you open the website.

**Comment by sschiessl-bcp** [comment] 2018-06-28 11:44
This was adressed by adding the "Connecting to ..." LoadingIndicator. My commit merely fixed a small bug in it.

**Comment by wmbutler** [comment] 2018-06-30 14:38
Closing this a duplicate of #1407

**Closed by wmbutler** 2018-06-30 14:38 UTC
Labels: duplicate
