### ISSUE TITLE
[3] Cancel Orders in bulk

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#558] opened 2017-10-11 10:08 UTC
I would like to have 3 Buttons to Cancel Orders na Open Orders Tab (and Exchange Tab)
1. cancel all orders in 1 step per trading pair
2. cancel all sell orders per trading pair in 1 step per trading pair
3. cancel all buy orders per trading pair in 1 step per trading pair

**Comment by landry314** [comment] 2017-10-11 14:03
Maybe this could be handled by a click-multi-select feature whereby multiple orders can be canceled with one confirm dialog so click-confirm-click-confirm-click-confirm can be avoided.

**Comment by wmbutler** [comment] 2017-10-11 19:44
Or maybe a filter in the Orders section with a select all to check the boxes and then a cancel button with a confirm?

**Comment by svk31** [comment] 2017-10-14 06:52
We could replace the delete button with checkboxes, and when at least one box is checked the delete icon appears in the header.

**Comment by wmbutler** [comment] 2017-10-20 13:09
Agreed. We can even do this in stages, but I really like the idea of first filtering for what you want and then being able to have a single checkbox in the header too.

Symbol | Quantity | [ ] 
-- | -- | --
bitUSD | 5 |  [ ] 
bitUSD | 10 |  [ ] 
bitUSD | 15 |  [ ] 
bitUSD | 7 |  [ ]

**Comment by wmbutler** [comment] 2017-10-20 13:23
I'm not in love with this, but it is functional.

![screen shot 2017-10-20 at 8 23 04 am](https://user-images.githubusercontent.com/1254810/31822908-eb58c10a-b56f-11e7-9186-54c858d463af.png)

**Comment by landry314** [comment] 2017-10-20 14:41
If you say "Cancel Orders" with an 's' it highlights the feature without any description.

**Comment by wmbutler** [comment] 2017-11-02 05:34
This was a tricky UX because naming a button "cancel" under these circumstances is definitely ambiguous.

**Comment by svk31** [comment] 2017-11-16 12:15
This UX isn't very clear imo. Is the submit button used to cancel orders once selected? What are we filtering on?

**Comment by wmbutler** [comment] 2017-11-16 14:11
- I think the filter should work on any portion of the asset pair column.
- [ ] We could slide the Submit / Reset buttons off to the right if you think that will bring more clarity. 
- I couldn't use the word 'cancel' for the cancel button
- Clicking on the word 'cancel' in the th could select all orders currently filtered by placing a check mark

**Comment by wmbutler** [comment] 2017-11-20 13:59
@calvinfroedge

**Comment by wmbutler** [comment] 2017-11-21 16:12
Pushing to 171201

**Comment by calvinfroedge** [comment] 2017-11-22 01:58
@wmbutler @svk31 This is mostly implemented [here](https://github.com/bitshares/bitshares-ui/tree/iss-558). 

However, one issue I'm running into is that each order requires a wallet unlock and confirmation. I tried passing some overrides to disable this, but then the issue is still that these cancellations execute at different times, resulting in multiple notifications and generally weird timing and an experience that seems buggy.

It would be preferable to have a single confirmation for cancelling all transactions, and have each of these execute at the same time.

I'm curious if we can perhaps make a change on core to allow for cancelling a group of order IDs, or if this functionality already exists there, so we can do this in one wallet transaction.

Thoughts?

**Comment by svk31** [comment] 2017-11-22 04:39
The functionality already exists to submit multiple operations in one transaction so you only get one confirmation dialog. Here's one example of this being done in the GUI code: https://github.com/bitshares/bitshares-ui/blob/staging/app/actions/MarketsActions.js#L378

Simply create a new action called `cancelOrdersBatch` or refactor `cancelLimitOrder`, pass it an array of IDs and loop over it as such: (adapted from current `cancelLimitOrder` action)

```
orderIDs.forEach(id => {
        tr.add_type_operation("limit_order_cancel", {
            fee: {
                amount: 0,
                asset_id: fee_asset_id
            },
            "fee_paying_account": accountID,
            "order": id
        });
}
```

**Comment by calvinfroedge** [comment] 2017-11-26 16:04
Closing issue as this was merged

**Closed by calvinfroedge** 2017-11-26 16:04 UTC
Labels: feature
