### ISSUE TITLE
[1.5][dot5enko][0.25][startailcoon] News does not load in light client

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#887] opened 2017-12-20 22:25 UTC
`app.js:53 Unhandled rejection TypeError: g is not a constructor`

**Comment by wmbutler** [comment] 2017-12-21 03:24
Might be nice to run this as a hotfix

**Comment by wmbutler** [comment] 2017-12-25 06:30
- [ ] News does not load in light client
- [ ] Date appears to be incorrect in some cases. This article shows a date of 21 Dec in the BTS wallet, but in STEEM, it says it was published 10 days ago (the current date as of this writing was Dec 25, implying an original publication date of 15 Dec.)

![screen shot 2017-12-25 at 12 27 10 am](https://user-images.githubusercontent.com/1254810/34334290-bec0c27c-e90a-11e7-94a6-aa7e9922db9b.png)
![screen shot 2017-12-25 at 12 27 05 am](https://user-images.githubusercontent.com/1254810/34334291-becf402c-e90a-11e7-98d7-fbe8f896df1d.png)
![screen shot 2017-12-25 at 12 26 49 am](https://user-images.githubusercontent.com/1254810/34334292-bede2678-e90a-11e7-9894-810397b0e708.png)

**Comment by wmbutler** [comment] 2017-12-25 06:30
+.5 for date bug fix as well.

**Comment by HarukaMa** [comment] 2017-12-26 22:25
`TypeError: WebSocket is not a constructor`
from `steem` package in `api/transports/ws.js`, seems it can't get package `ws` in electron.

Date bug fix is in #913.

**Comment by wmbutler** [comment] 2017-12-26 23:07
@HarukaMa are you planning to claim the Light Client fix as well or do I need to break this into 2 issues?

**Comment by dot5enko** [comment] 2017-12-27 00:31
i can take over light client bug if @HarukaMa would not claim it

**Comment by wmbutler** [comment] 2017-12-27 02:02
@dot5enko it's yours.

**Comment by dot5enko** [comment] 2017-12-28 03:09
@svk31, the problem is in [steem library](https://github.com/steemit/steem-js/blob/3312d5ab0732ecb69a76e816c131985454d55748/src/api/transports/ws.js#L9), after webpack it turns to be empty object which cause an error. 
I came up to [stackoverflow](https://stackoverflow.com/questions/38289019/require-webpack-bundle-returns-empty-object) with similar problem but it changed nothing, so i need a help of someone experienced with webpack.

**Comment by dot5enko** [comment] 2018-01-03 11:09
@svk31 can you help me with this ?

**Comment by wmbutler** [comment] 2018-01-06 17:27
@svk31 did this make it into the current release? If not, please push, otherwise close.

**Comment by wmbutler** [comment] 2018-02-02 00:46
- [ ] News isn't loading in the web wallet now.

**Comment by startailcoon** [comment] 2018-02-11 09:40
News is now loading again, as the issue was the API URL the client was trying to load from wasn't correct.
This section still needs some love though.

**Closed** 2018-02-12 13:06 UTC
Labels: bug
