### ISSUE TITLE
fail to create account

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-ui#319] opened 2017-08-24 10:48 UTC
I compile witness nodes with private network test, 
my rpc-endpoint is 10.0.0.228:11011, and I set the api-access with 10.0.0.228:11011, faucet address as https://10.0.0.228, 

it shows connected status. but when I create account it shows me with unknow error. do you know why?
[10.0.0.228-1503572342190.TXT](https://github.com/bitshares/bitshares-ui/files/1248580/10.0.0.228-1503572342190.TXT)

**Comment by abitmore** [comment] 2017-08-24 10:51
More info please.

**Comment by cxxcunow** [comment] 2017-08-24 11:12
I update with web log above

**Comment by svk31** [comment] 2017-08-25 14:53
Duplicate of #324

**Closed by svk31** 2017-08-25 14:53 UTC
Labels: question
