### ISSUE TITLE
[Tradingview] - no chart update

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2714] opened 2019-05-26 22:26 UTC
**Describe the bug**
Tradingview doesn't update chart, when using the market button from asset info page

**To Reproduce**
1. USD tab
2. OPEN.EOS -> (OPEN.EOS/bitUSD)
3. Market Picker: OPEN.EOS
4. Find an asset to replace [open.EOS](url)
5. By clicking on open.EOS, I get to Asset info page
6. Clicking on market I get to open.EOS/BTS, but the Tradingview chart still shows OPEN.EOS/bitUSD chart

**Expected behavior**
Update Tradingview chart

**Screenshots**
![Tradingview](https://user-images.githubusercontent.com/40874087/58387815-c936ef80-8015-11e9-9ebd-c6e1b01bee52.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Light clien: 190424

**Comment by froooze** [comment] 2019-05-26 22:33
#2473?

**Comment by startailcoon** [comment] 2019-05-28 19:48
Duplicate of #2473

**Closed by startailcoon** 2019-05-28 19:48 UTC
Labels: [0] Duplicate
