### ISSUE TITLE
[1] Wierd appearance of account "jesus-coin" in completely new wallet

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#1403] opened 2018-04-04 16:13 UTC
I created a new wallet with a new passphrase, registered a new account, sent it some BTS and upgraded it to LTM, all using the openledger.io. I backed up the new wallet with one account in it, and opened it up in the light client (2.0.180404) Using Win7. The wallet opened up not using the account I created but into this "jesus-coin" -account. I was able to read memo's and view supposed private keys. It also displayed _brainkey position_:
![image](https://user-images.githubusercontent.com/6001014/38319812-7682d7a4-383b-11e8-841d-9a4a679c45e8.png)

I attempted adding that account owner and active permissions for my own account, with the intention to remove original keys. The transaction didn't succeed using the light wallet - the save button just didn't respond. I then did the same using openledger.io, and it appeared to succeed - the transaction was approved. However I didn't get owner or active permissions added to the jesus-coin account, and am now unable to view messages or private keys any more. The UI still displays brainkey position.

I'm still trying to figure out what happened. Someone had earlier sent the account 3 BTS with the message "your account appeared wierdly" or something similar.

**Comment by abitmore** [comment] 2018-04-04 19:04
I've heard of this for several times, but nobody was able to stably reproduce it. I guess active key of that account is special.

**Comment by happyconcepts** [comment] 2018-04-05 03:04
Is jesus-coin your account or someone else's? Also, what is brainkey position?

**Comment by MarkoPaasila** [comment] 2018-04-05 07:17
@happyconcepts jesus-coin is not my account. Brainkey position indicates the sequence of deriving new keys deterministically from a brain key.

**Comment by abitmore** [comment] 2018-04-05 08:48
Other reports is here (in Chinese): https://bitsharestalk.org/index.php?topic=25623.0

@MarkoPaasila if you can't show the private key of that account any more, I don't think the brain key would help. Actually I have never looked into the brain key stuff yet, so don't give it to me. Wish someone else can help.

**Comment by HarukaMa** [comment] 2018-09-18 07:28
Reviving this as I was reproducing on my development environment.

This time we have:
![image 0030-09-18 16 19 29](https://user-images.githubusercontent.com/861659/45670770-9f602b80-bb5e-11e8-8eda-dacd27743714.jpg)
![image 0030-09-18 16 19 33](https://user-images.githubusercontent.com/861659/45670772-a129ef00-bb5e-11e8-8c12-96ebe255d449.jpg)

which involves these accounts:
![image 0030-09-18 16 19 48](https://user-images.githubusercontent.com/861659/45670782-aa1ac080-bb5e-11e8-9b04-8212d413bfd5.jpg)

They both have same keys for owner and active, and both have brain key position 0 and 1. This strongly suggests that somehow brain key generator was giving out default non-randomized values.

After debugging I was able to extract the private key from the brain key seed and saved it locally. I don't know if I should paste the keys here, but `sha1 hash of your brainkey: e61a` in case someone else also reproduced it on this set of accounts.

**Comment by abitmore** [comment] 2018-09-18 08:52
We found the reason. The generated brain key is not used, instead, an empty string was used to derive the public keys. I guess we can add an assertion somewhere in the public/private key pair derivation code, if the input is empty, refused to execute and throw an error?

**Comment by MarkoPaasila** [comment] 2018-09-19 05:01
Does this mean that anyone for whom this happens get's access to all other accounts generated this way?

**Comment by abitmore** [comment] 2018-09-19 12:59
That means we (and anyone who know how to do it) now have access to all those accounts because we now know the private keys. Specifically, 11 accounts, with total balance around 0.2 BTS. If a new account created with same public key, we'll have access as well.

Normal accounts aren't affected.

**Comment by wmbutler** [comment] 2018-09-25 20:54
Fixed at bitsharesjs end. @clockworkgr will you close this since the issue was at bitsharesjs or make mods here if we need to be able the response that no account can be created.

**Comment by clockworkgr** [comment] 2018-09-26 14:47
well, iirc the UI simply displays errors coming from bitsharesjs and the backend so I don't think there's anything more to be done unless you wanna make the error prettier.

It's so rare I don't think anything is needed though. This is simply making sure no more accounts like this are created.

Don't have permissions to close this though.

**Comment by clockworkgr** [comment] 2018-09-27 06:43
Also, perhaps better to keep this open until sigve returns and the bitsharesjs PR is merged upstream and dependency here updated.

**Comment by sschiessl-bcp** [comment] 2018-10-02 17:41
Great news this is finally be solved!

**Comment by wmbutler** [comment] 2018-10-02 18:34
@sschiessl-bcp since you are taking over for @svk31 please close this once merged.

**Closed** 2018-10-09 07:46 UTC
Labels: task
