### ISSUE TITLE
[1.5][abitmore] User executed a buy order for the exact sell order and trade is not going through

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#562] opened 2017-10-11 19:29 UTC
200 PRIVATECAY for .4 LTC/PRIVATECAY were available for sale. The user clicked on lowest ask and committed all of their OPEN.LTC by clicking on their balance.

As you can see, the trade did not go through.

The intended behavior is that the trade would execute since the buyer offered at the lowest ask. I can leave this order on the books to allow for testing.

![screen shot 2017-10-11 at 2 23 05 pm](https://user-images.githubusercontent.com/1254810/31461949-96530c14-ae90-11e7-86ed-0d2b66aea3c9.png)

**Comment by abitmore** [comment] 2017-10-11 19:47
The *OLD* rounding issue. The price is not exactly same.

**Comment by wmbutler** [comment] 2017-10-11 19:49
This needs to be researched in the UI. We've got to get this right. The PRIVATECAY asset has a fee when tokens are purchased. This might be causing some of the issue.

**Comment by abitmore** [comment] 2017-10-11 19:51
`4.85598541 / 121.39964 = 0.0399999984 < 0.4 = 8/200`

This issue has been in discussion long long before, and still on going. Not an easy fix IMHO.

**Comment by abitmore** [comment] 2017-10-11 19:56
Seems duplicate of #314?

**Comment by wmbutler** [comment] 2017-10-11 20:05
The GUI generated both of those first numbers though through clicks. I feel like this is a garbage in / garbage out issue. @xeroc could really use your help on this one as well. I understand that it's a long standing problem, but issues like this are very hard to explain to average people.

The GUI calculated the number of shares of PRIVATECAY based upon 2 inputs

- qty OPEN.LTC
- Lowest ask

Maybe we need to alter the Balance amount so it's evenly divisible forcing the numbers to match evenly. This would allow for the number to remain the same throughout the entire flow (Balance, Qty, Confirmation)

**Comment by abitmore** [comment] 2017-10-11 20:18
I think it's related to #497.
By clicking, the UI should make sure the order can go through. If the user changed an amount afterwards, the UI should make sure the order can still go through. If the user changed the price, that's another story.

**Comment by svk31** [comment] 2017-10-11 20:37
No it's not related to 497, it's the age old of issue of trying to match orders without knowing how the backend actually makes matches, and trying to round amounts correctly when the amounts become inexact due to precisions.

**Comment by abitmore** [comment] 2017-10-11 21:36
The logic in the back end is simple: the order will match if the bid price is not lower than lowest ask.
```
price = base_amount / quote_amount
=> 
new_bid.price = new_bid.base_amount / new_bid.quote_amount
lowest_ask.price = lowest_ask.base_amount / lowest_ask.quote_amout
=> 
new_bid.price >= lowest_ask.price
=>
new_bid.base_amount / new_bid.quote_amount >= lowest_ask.base_amount / lowest_ask.quote_amout
=>
new_bid.base_amount * lowest_ask.quote_amount >= lowest_ask.base_amount * new_bid.quote_amout
```
Amounts are integers, so, all final calculations SHOULD use the amounts but NOT the prices, since prices are usually float points thus inaccurate. In addition, use multiplications and avoid divisions at least for the final check.

**Comment by abitmore** [comment] 2017-10-12 00:26
Reproduce:
* open https://bitshares.org/wallet/#/market/PRIVATECAY_OPEN.LTC, in the "buy PRIVATECAY" area, input `4.85598541` as LTC amount, then click `lowest ask`, the PRIVATECAY amount will appear as `121.39964` which is incorrect
* if click the price first, then input LTC amount, the PRIVATECAY amount will appear as `121.39963` which is correct
* In flipped market, "sell PRIVATECAY" area, behaviors when inputting LTC amount are correct.

The key is: when placing a new order, in order to successfully match, `amount_to_sell` should be always rounded up and `amount_to_receive` should be always rounded down. So, everywhere in Exchange.jsx, the code SHOULD always be
```
_setForSale(xxx, true);
```
and
```
_setReceive(xxx, false);
```

The behaviors when inputting amounts are correct because
* `isBid` passed into `_onInputSell()` is always `false` which will call `_setReceive(xxx,false)` and
* `isBid` passed into `_onInputReceive()` is always `true` which will call `_setForSale(xxx,true)`

These lines are incorrect: [here](https://github.com/bitshares/bitshares-ui/blob/2.0.171009/app/components/Exchange/Exchange.jsx#L539-L540), [here](https://github.com/bitshares/bitshares-ui/blob/2.0.171009/app/components/Exchange/Exchange.jsx#L780-L784), [here](https://github.com/bitshares/bitshares-ui/blob/2.0.171009/app/components/Exchange/Exchange.jsx#L585-L589) and [here](https://github.com/bitshares/bitshares-ui/blob/2.0.171009/app/components/Exchange/Exchange.jsx#L623-L627).

Actually, perhaps we can always call `times(xxx,true)` in `_setForSale` and call `times(xxx,false)` in `_setReceive`.

I will submit a PR.

**Comment by svk31** [comment] 2017-10-12 10:12
abit's commit might have solved it, as always with this issue only time will tell..

**Comment by wmbutler** [comment] 2017-10-12 12:33
Agreed. We can keep iterating until we catch all the edge cases. Thanks for your work@abitmore

**Closed** 2017-10-13 08:15 UTC
Labels: bug, high priority
