### ISSUE TITLE
"Issue Asset" and "cancel" buttons are dead

### ISSUE THREAD

**Issue by neo-thematrix** [bitshares/bitshares-ui#1424] opened 2018-04-12 23:26 UTC
Failed on three different browsers on both linux ubuntu and windows 10 and also fresh install of the light client.
![screenshot from 2018-04-12 16-40-58](https://user-images.githubusercontent.com/7365837/38709128-8e114432-3e76-11e8-967f-92e4a9af13d9.png)

I was able to issue UIA with openledger's site with no issue.

**Comment by startailcoon** [comment] 2018-04-13 04:06
Fixed for next release.
Duplicate of Issue #1395

**Closed** 2018-04-13 04:06 UTC
