### ISSUE TITLE
chart area scroll 

### ISSUE THREAD

**Issue by pstrident** [bitshares/bitshares-ui#1565] opened 2018-05-29 21:22 UTC
scrolling down in the chart area to bid and offers has been removed.

please reinstall it..

tradingview looks great though...

tia
pstrident

**Comment by svk31** [comment] 2018-05-30 06:00
Incorrect. Please search for existing issues before cresting new ones. Duplicate of https://github.com/bitshares/bitshares-ui/issues/1549

**Closed by svk31** 2018-05-30 06:00 UTC
