### ISSUE TITLE
[.5] Final entry in Market history gets cut off (css issue)

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-ui#1762] opened 2018-08-06 04:37 UTC
**Describe the bug**
Cannot see all Market Trades (see screenshot below) BitShares-UI 180720 in Chrome & Desktop Ubuntu 16.04 64bit

**Screenshots**
![market trades ui bug](https://user-images.githubusercontent.com/36471515/43697238-8083786e-994b-11e8-8573-982b920b5b44.png)

**Comment by sschiessl-bcp** [comment] 2018-08-06 05:27
Can you be more specific?
What orders are missing? How can we reproduce?

**Comment by cogutvalera** [comment] 2018-08-06 06:02
isn't my screenshot specific as much as possible ? :-) look please more accurately on my screenshot and you will understand that I cannot scroll down in Market Trades panel to see other orders, I don't know which exactly orders I don't see because I cannot see them.

**Comment by svk31** [comment] 2018-08-06 10:33
I do now, hence the title change, but it took some time to figure out and that's quite annoying when it would've been so easy to just explain what the issue was.

**Comment by cogutvalera** [comment] 2018-08-06 10:53
I've described the bug and showed screenshot, I didn't just place only screenshot without any describing words.

"Cannot see all Market Trades" - is it so hard to understand ? isn't it self explanatory in conjuction with my screenshot ? I don't think that for this little bug we need a lot of describing words, right ? isn't so ?

**Comment by cogutvalera** [comment] 2018-08-06 11:16
sorry if I've wasted your time ! Really sorry ! I really appreciate all your efforts and your time as well ! I don't like also when people tells about bugs without any directions and descriptions or with just a few describing words about founded bugs which isn't enough in most cases, it's really annoying ! You're absolutely right ! At the same time I don't like a lot of words when it isn't required really. I like brevity in all cases. Sorry if I've confused you even just a little ;-)

**Comment by startailcoon** [comment] 2018-08-06 19:00
I can say that this really took me some time to see as well, and I think it would have been much help to describe what the issue was in more detail *OR* made a circle on the image pointing to the actual issue.

Something that may have looked obvious to you can take some time for someone else. At least the issue is defined and can be fixed now.

For the record for those still trying to find this issue. The table labeled "Market Trades" isn't using the full height. 

![image](https://user-images.githubusercontent.com/12114550/43735755-bad8a816-99bb-11e8-8fc4-fdc9199cb381.png)

**Comment by cogutvalera** [comment] 2018-08-06 19:10
Perfect ! Really forgot about RED CIRCLE in screenshot ! My fault ! Sorry !

**Comment by cogutvalera** [comment] 2018-08-07 18:16
also it seems like MY OPEN ORDERS table is cutted off (the same bug as for MARKET TRADES)

**Comment by startailcoon** [comment] 2018-08-07 18:39
It's not exactly cut of, it's just not spanning all the space it have when the boxes on the same row are taller.

**Comment by cogutvalera** [comment] 2018-08-07 18:41
@startailcoon I think the same, but used "cut off" as @svk31 mentioned in title

**Comment by svk31** [comment] 2018-08-17 06:50
I'm unable to reproduce this on my end, the orders align perfectly with scrollbox here.

**Comment by startailcoon** [comment] 2018-08-17 13:43
I think OP refers to the unused space below the box. Also visible on your screenshot.

**Comment by svk31** [comment] 2018-08-18 05:52
No, in his screenshot part of the last line is not visible even though he's scrolled all the way down.

**Comment by startailcoon** [comment] 2018-08-18 06:32
Oh, didn't catch that. You're right 👍

**Comment by startailcoon** [comment] 2018-09-24 16:19
This will be fixed part of the Exchange Redesign.
Closing.

**Closed by startailcoon** 2018-09-24 16:19 UTC
Labels: bug, staging

**Comment by wmbutler** [comment] 2018-09-28 15:33
Marked as duplicate since it will be resolved in exchange redesign.
