### ISSUE TITLE
[1.5][kapeer42] Sorting on price change in portfolio

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1328] opened 2018-03-15 22:42 UTC
When the price of an asset changes and updates the portfolio page, it briefly unsorts everything and then reverts back to the chosen sort order. I captured the activity in a licecap. I gave it 1.5 because it might be hard to reproduce.

![flash](https://user-images.githubusercontent.com/1254810/37494741-3b9bafc6-2878-11e8-9b4b-6cd567312bbd.gif)

**Comment by svk31** [comment] 2018-03-16 16:37
Could be a duplicate of https://github.com/bitshares/bitshares-ui/issues/1202

**Comment by calvinfroedge** [comment] 2018-03-25 17:53
Would really need clear reproduce steps in order to resolve this

**Comment by wmbutler** [comment] 2018-03-25 18:17
@calvinfroedge you need to have assets that update frequently. Maybe you can observe some accounts with bitUSD, BTS, bitCNY. Sort them and just watch them shift as the values change. I'll add time if it takes time to reproduce but in my experience it was easy to see in under a 2-5 minute span.

**Comment by kapeer42** [comment] 2018-04-20 19:44
Can I claim this?

**Closed** 2018-05-01 08:59 UTC
Labels: bug

**Comment by svk31** [comment] 2018-05-01 09:01
The PR was not fixing the issue, but while investigating I discovered an issue with the sorting that I fixed and the sorting is now stable.
