### ISSUE TITLE
[.5] When viewing market depth chart, page jumps back to top every few seconds.

### ISSUE THREAD

**Issue by knifewine** [bitshares/bitshares-ui#410] opened 2017-09-15 12:54 UTC
This seems unique to the market depth chart (doesn't seem to happen on the price chart). Looks like it might be when some data changes in the chart or elsewhere on the page.

To repro:
Go to a market, such as BTS:bitUSD.
Click DEPTH CHART.
Scroll the page down to the bottom.
Wait for a 5-10 seconds and the page will jump back to the top.
Not critical, but definitely annoying.

I'm using the debian package, version 170915.

**Comment by wmbutler** [comment] 2017-09-15 17:40
Possibly related to #370

**Comment by svk31** [comment] 2017-09-15 17:51
Yes it's a duplicate of #370.

**Closed by svk31** 2017-09-15 17:51 UTC
Labels: bug
