### ISSUE TITLE
[10] Troubleshooting connection problems 

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1228] opened 2018-02-28 14:42 UTC
This issue is for the "Out of sync" issue and generally laggy behavior that occurs at times in the UI. 
This will be a joint work from the UI and the infrastructure worker as the problem might be on either side.

In the first step I would like to collect symptoms that manifest and possible ideas as to why it happens and when it happens.

Please comment any and all ideas and suggestions that help to decide how to properly tackle this issue.

Stefan Schießl 
Blockchain Projects BV

**Comment by wmbutler** [comment] 2018-02-28 14:46
From my perspective, this appears to happen arbitrarily not necessarily based on a particular operation. I think we need to have some socket console logs in the browser added so we can observe the pre and post events associated with a socket disconnect.

These logs could be added to the branch representing this issue.

**Comment by svk31** [comment] 2018-02-28 14:49
For reference the code checking if the blockchain of the API node is out of sync is located here: https://github.com/bitshares/bitsharesjs/blob/master/lib/chain/src/ChainStore.js#L141

It's treated as out of sync if the timestamp of the current node is more than 60s in the past compared to the user's local clock.

**Comment by ahdigital** [comment] 2018-02-28 15:04
Just adding some notes from my experience with this issue:

Yesterday, I was viewing some accounts with lots of assets and the browser was hanging whilst trying to connect to ol-api1.openledger.info

I just checked network tab on the portfolio page for my account and it connects to these addresses:

- wss://eu.nodes.bitshares.ws/
- https://ol-api1.openledger.info/api/v0/ol/support/coins
- https://ol-api1.openledger.info/api/v0/ol/support/trading-pairs
- https://ol-api1.openledger.info/api/v0/ol/support/active-wallets
- https://ol-api1.openledger.info/api/v0/ol/support/coins
- https://api.blocktrades.us/v2/trading-pairs
- https://ol-api1.openledger.info/api/v0/ol/support/active-wallets

**Comment by wmbutler** [comment] 2018-02-28 15:12
Possible thought is to render the Withdraw / Deposit buttons based on a static list to avoid these constant calls:

```
OPEN.*, RUDEX.*, BRIDGE.*, GDEX.*
```

**Comment by svk31** [comment] 2018-02-28 15:14
That's unrelated @wmbutler, the connection issue is with the websocket connection

**Comment by wmbutler** [comment] 2018-02-28 15:32
We are double calling OL with every switch between dashboard and exchange.

![calls](https://user-images.githubusercontent.com/1254810/36796059-3cefbc10-1c6a-11e8-9ab6-3efd3e494af6.gif)

**Comment by svk31** [comment] 2018-02-28 15:37
Also not a big deal, but I think the call in Exchange.jsx is a remnant from when we had quick buy functionality from Blocktrades in the Buy/Sell forms. I can remove it.

**Comment by sschiessl-bcp** [comment] 2018-03-06 16:06
Rumors say that an ongoing margin call is flooding the websocket connection.
Investigation on the backend here is necessary.

I will start digging through the ChainStore just so see and understand what happens.

**Comment by wmbutler** [comment] 2018-03-08 05:43
I do notice

- higher latency
- more frequent socket disconnects

during high volume trading periods and margin calls.

**Comment by sschiessl-bcp** [comment] 2018-03-08 10:24
Still digging and getting familiar ...

The first thing I noticed is [https://github.com/bitshares/bitshares-ui/blob/staging/app/components/Utility/BindToChainState.jsx](BindToChainState).

It has console.log lines that are commented at the moment indicating that there was already debugging going on. When I enable the logs and look what is happening within this central component its quite heavy loaded. Right now there is no connection issue and the activity is moderate, but that component is working like crazy.  I think the debugging is from you @svk31 ?

I am not sure if this is causing out of sync, but I can see that this central component can probably use optimizing. It has a lot of for loops and actions inbetween. My suggestion would be to properly abstract the logic of the for loops (seem all similar) in order to remove code copies and then squeeze our brains to see if it can be optimized in some way.

Thoughts?

**Comment by wmbutler** [comment] 2018-03-09 00:27
@calvinfroedge might be a fun one for you to tackle. @svk31 any interest?

**Comment by svk31** [comment] 2018-03-09 07:35
I doubt that component has anything directly to do with the connection issues since it's only a wrapper asking for data from the ChainStore, which in turn handles API requests for objects using https://github.com/bitshares/bitsharesjs-ws. BindToChainState used to be a decorator but is now used as a Higher Order Component (HOC) which is a React pattern for adding functionality to components. It is used to resolve an object id ("1.3.0") to a full object from the blockchain via the ChainStore.

I've actually done a pass on BindToChainState just recently to improve its performance as I noticed that the setState call was quite expensive for some reason. As to the for loops, they have hardly any impact on the performance of the component. In most cases BindToChainState only resolves one object, say an asset, so the loop will do one iteration over an array containing one entry. So even though there are multiple loops to handle resolution of different types of objects, each instance of BindToChainState will generally only use one of them.

I think a better place to investigate would be routerTransition.js, which is basically the init function of the app. It's called by react-router on app load and initializes the database and websocket connection among other things. bitsharesjs-ws could probably also be improved.

**Comment by sschiessl-bcp** [comment] 2018-03-15 13:39
Progress is slow, trying to dig and understand. 
Currently down to ChainWebSocket and https://github.com/websockets/ws

Any tips on proper debugging, how to proceed and help is appreciated

**Comment by litepresence** [comment] 2018-03-15 23:33
hi I am using this tool I dev'd recently to determine websocket latency, please take a look: https://github.com/litepresence/extinction-event/blob/master/bitshares-node-latency.py

**Comment by litepresence** [comment] 2018-03-15 23:36
also, I'd like to comment that when using the UI the node latency in settings>>access never updates and it seems that any node with latency greater than 3 seconds states "unreachable" while I know there are many more reachable than stated.  I am in an area where node latency is typically 3-5 seconds... so UI usually tells me no nodes are reachable; maybe one or two

**Comment by wmbutler** [comment] 2018-03-15 23:41
@sschiessl-bcp I invited @litepresence to work on this as well since he seems motivated.

**Comment by litepresence** [comment] 2018-03-15 23:48
something I have noticed in multiple tests of node latency is that ending all websockets with /wss suffix increases chance of success in connecting, with the exception of three which prefer /ws suffix, ['wss://relinked.com/ws',  'wss://bitshares.crypto.fans/ws', 'wss://this.uptick.rocks/ws']  You can test this by running my script with arg "suffix=True"

**Comment by litepresence** [comment] 2018-03-15 23:53
re: "It's treated as out of sync if the timestamp of the current node is more than 60s" this should not be the case.  Should always be less than 4 seconds (3 really, but I use 4 as failsafe) , perhaps you are not actually looking at the "head" block and are looking at last "irreversible" block?  this often is 60 seconds delayed. w/ pybitshares I use the "mode" arg when calling blockchain, see: http://docs.pybitshares.com/en/latest/bitshares.blockchain.html

**Comment by litepresence** [comment] 2018-03-16 00:11
I just removed/hide all nodes that were listed in settings>>access, then I added all the nodes listed as GOOD here: https://pastebin.com/Zs2AYFi5 (note they all have /wss or /ws extensions).   I closed and reopened my UI.  upon reopening I have the lowest latencies I've ever seen on the UI and more listed as available than I've ever seen with the default websocket choices; several under 1 second.

**Comment by litepresence** [comment] 2018-03-16 00:11
that pastebin was produced using my python script above

**Comment by wmbutler** [comment] 2018-03-16 00:33
@litepresence Understand that this issue is about more than just the connection and timing. It's also related to traffic on the connection while active and understanding what the root causes of disconnections are.

**Comment by litepresence** [comment] 2018-03-16 01:49
I understand, can you link me to some of the most likely subsections of code?  I write python, but I can generally polyglot read

**Comment by litepresence** [comment] 2018-03-16 15:27
these are four nodes listed in the gui that come up as "unreachable" but I believe they are simply malformed addresses, as I have contacted them thus:

wss://ws.winex.pro | Unreachable
wss://ws.winex.pro/wss | Available
wss://us.nodes.bitshares.ws | Unreachable
wss://us.nodes.bitshares.works/wss | Available
wss://eu.nodes.bitshares.ws | Unreachable
wss://eu.nodes.bitshares.works/wss | Available
wss://api.bts.blckchnd.com | Unreachable
wss://api.bts.blckchnd.com/wss | Available

**Comment by litepresence** [comment] 2018-03-16 16:17
regarding the 4 nodes above, I run them through my ping script... and they all connect without issue no matter what extension I use:

('ping:', '1.41', 'wss://api.bts.blckchnd.com')
('ping:', '1.57', 'wss://api.bts.blckchnd.com/ws')
('ping:', '1.55', 'wss://api.bts.blckchnd.com/wss')
('ping:', '1.49', 'wss://eu.nodes.bitshares.works')
('ping:', '1.46', 'wss://eu.nodes.bitshares.works/ws')
('ping:', '1.54', 'wss://eu.nodes.bitshares.works/wss')
('ping:', '1.80', 'wss://eu.nodes.bitshares.ws')
('ping:', '1.54', 'wss://eu.nodes.bitshares.ws/ws')
('ping:', '1.46', 'wss://eu.nodes.bitshares.ws/wss')
('ping:', '1.47', 'wss://us.nodes.bitshares.works')
('ping:', '1.40', 'wss://us.nodes.bitshares.works/ws')
('ping:', '1.44', 'wss://us.nodes.bitshares.works/wss')
('ping:', '1.58', 'wss://us.nodes.bitshares.ws')
('ping:', '1.89', 'wss://us.nodes.bitshares.ws/ws')
('ping:', '1.39', 'wss://us.nodes.bitshares.ws/wss')
('ping:', '3.25', 'wss://ws.winex.pro')
('ping:', '2.89', 'wss://ws.winex.pro/ws')
('ping:', '2.88', 'wss://ws.winex.pro/wss')

**Comment by litepresence** [comment] 2018-03-16 16:24
ok disregard last finding, apparently UI is not ping testing nodes listed in "hidden" so that was all I was finding.  so much for that

**Comment by litepresence** [comment] 2018-03-20 20:55
I realize ideal is "understanding what the root causes of disconnections" and stopping that from happening.   However, when node goes down and app displays "lost connection" why even display that? why not just ping each of whitelisted nodes again... find fastest node and reconnect?  Why wait for user to initiate that manually?

**Comment by wmbutler** [comment] 2018-03-24 14:38
@litepresence I agree in principle with what you are saying. To some degree, it's good to feel the pain of having to manually connect in order to force us to fix the underlying problem, but I do see your point and it is valid.

**Comment by litepresence** [comment] 2018-03-26 00:07
https://pastebin.com/0YWD0Qn2

**Comment by sschiessl-bcp** [comment] 2018-03-29 10:38
I committed the refactor. I tested the connection handling and it seems like I didn't break anything.
I was really scrubbing it hard to find the hidden logic and switches and tried to make it more easier understandable.
See the branch
https://github.com/blockchainprojects/bitshares-ui/tree/access-setting
mainly the last commit
https://github.com/blockchainprojects/bitshares-ui/commit/70a1883a8b917225334ae2c7625b2194f559a81c

Please do give me feedback, I can do a PR if it makes it easier.

**Comment by wmbutler** [comment] 2018-04-01 17:54
Should I close this out? I feel like we've put a lot of effort into this and we can put it to rest until we run across some edge cases.

**Comment by sschiessl-bcp** [comment] 2018-04-01 17:59
I'm actively working on it, see my last comment

**Comment by sschiessl-bcp** [comment] 2018-05-07 11:56
I think this can be closed with the work on the backend with disabling the callback on everything and the refactoring which caught some of the bugs.

For reconnection robustness and stability there are already issues open out there which I am happy to address next.

Most of my work here was the refactoring and investigation, I am honestly not sure about the exact hours I spent on this but it helped me a lot getting to know everything. I am fine with the appointed hours, if you are as well @wmbutler , let's close this.

**Closed** 2018-05-07 14:14 UTC
Labels: bug
