### ISSUE TITLE
No ability to login/create Wallet Account on Staging HIGH PRIORITY

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1168] opened 2018-02-14 14:34 UTC
This issue a part of discussion: #1167

![gif-cannot-login-using-wallet-account](https://user-images.githubusercontent.com/35899973/36209642-854dd0a6-119c-11e8-9461-e07b428fec1c.gif)

The proposal is at least revert `Create account` button to header to make users able to go to [Create Account](https://wallet.bitshares.org/#/create-account) page where they can create any type of account or login under any type of account.

**Comment by gibbsfromncis** [comment] 2018-02-14 14:36
Why there are "Add contact" button? Which contact can I add if I even not logged in??

<img width="1440" alt="screenshot 2018-02-14 15 35 30" src="https://user-images.githubusercontent.com/35899973/36209690-bb9f945a-119c-11e8-8003-dea06daf4a5f.png">

**Comment by gibbsfromncis** [comment] 2018-02-14 14:37
@svk31 @wmbutler guys we cannot deploy this. And I think we should investigate why this happened. Why those changes are on `staging` before Sprint end...

**Comment by ahdigital** [comment] 2018-02-14 15:12
I've found that since PR #1143 the redirection to the login selector page has gone. It was the login selector page where I used to login using a password or choose to restore and login with local wallet.

The only way I can see now is to go to settings and toggle the login mode.

**Comment by startailcoon** [comment] 2018-02-14 15:40
#1143 should not have this effect. Some other PR merged with staging prior to it is responsible for this change.

We should find and revert this change. Does #1140 have anything to do with this?

**Comment by ahdigital** [comment] 2018-02-14 15:43
I rolled back to #1140 and it works for me, but that is before the header/dashboard tweaks.

**Comment by zhyupe** [comment] 2018-02-21 05:41
The missing welcome page for new user(landing page) is caused by #1142. I'm sorry for that and have fixed it in the new pr #1193..

**Comment by svk31** [comment] 2018-02-27 09:09
This was fixed by reverting the original PR.

**Closed by svk31** 2018-02-27 09:09 UTC
