### ISSUE TITLE
how about remove the dust trade from bars?

### ISSUE THREAD

**Issue by gpmn** [bitshares/bitshares-ui#713] opened 2017-11-08 07:34 UTC
the dust trade twist the graph heavily,  think about this suggestion, please

**Comment by svk31** [comment] 2017-11-08 11:50
Closed as duplicate of a million other issues. It's not something that can be done in the GUI, waiting on the backend to fix it.

**Closed by svk31** 2017-11-08 11:50 UTC

**Comment by abitmore** [comment] 2017-11-08 18:57
This is duplicate of #200.
@svk31: any progress about https://github.com/bitshares/bitshares-core/pull/455 which is expected to fix this? If it's OK we will merge it.
