### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by blackparallax** [bitshares/bitshares-ui#1958] opened 2018-10-08 11:45 UTC
bitshares-ui$ npm run package-deb

> BitShares2-light@2.0.181010-rc1 package-deb /home/blackparallax/Cryptocurrency/bitshares-ui
> npm run prepackage && build  -p never --linux deb

> BitShares2-light@2.0.181010-rc1 prepackage /home/blackparallax/Cryptocurrency/bitshares-ui
> npm run build-electron

> BitShares2-light@2.0.181010-rc1 build-electron /home/blackparallax/Cryptocurrency/bitshares-ui
> cross-env NODE_ENV=production webpack --env.prod --env.electron --env.hash

/home/blackparallax/Cryptocurrency/bitshares-ui/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
		                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/blackparallax/Cryptocurrency/bitshares-ui/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/blackparallax/Cryptocurrency/bitshares-ui/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/blackparallax/Cryptocurrency/bitshares-ui/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

npm ERR! Linux 4.15.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build-electron"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! BitShares2-light@2.0.181010-rc1 build-electron: `cross-env NODE_ENV=production webpack --env.prod --env.electron --env.hash`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BitShares2-light@2.0.181010-rc1 build-electron script 'cross-env NODE_ENV=production webpack --env.prod --env.electron --env.hash'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the BitShares2-light package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --env.prod --env.electron --env.hash
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs BitShares2-light
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls BitShares2-light
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/blackparallax/Cryptocurrency/bitshares-ui/npm-debug.log

npm ERR! Linux 4.15.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "prepackage"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! BitShares2-light@2.0.181010-rc1 prepackage: `npm run build-electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BitShares2-light@2.0.181010-rc1 prepackage script 'npm run build-electron'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the BitShares2-light package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-electron
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs BitShares2-light
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls BitShares2-light
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/blackparallax/Cryptocurrency/bitshares-ui/npm-debug.log

npm ERR! Linux 4.15.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "package-deb"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! BitShares2-light@2.0.181010-rc1 package-deb: `npm run prepackage && build  -p never --linux deb`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BitShares2-light@2.0.181010-rc1 package-deb script 'npm run prepackage && build  -p never --linux deb'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the BitShares2-light package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prepackage && build  -p never --linux deb
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs BitShares2-light
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls BitShares2-light
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/blackparallax/Cryptocurrency/bitshares-ui/npm-debug.log

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04LTS
 - Browser Firefox 62.0.3 (64-bit)

[npm-debug.log](https://github.com/bitshares/bitshares-ui/files/2455756/npm-debug.log)

**Comment by svk31** [comment] 2018-10-11 07:46
Unable to reproduce, builds fine on my computer. Try reinstalling your node modules with `npm i`.

Because of changes to alt-react old rc builds won't work without making a temporary modification, but that's a different issue. The modification is explained here: https://github.com/bitshares/bitshares-ui/issues/1965#issuecomment-428371219

**Comment by Zapata** [comment] 2018-10-19 16:40
I have the same issue using 2.0.181010 branch and below Dockerfile:
```
FROM node:6 as build

RUN npm install -g cross-env
ADD . /bitshares-ui
WORKDIR /bitshares-ui
RUN cross-env npm install --env.prod
RUN npm run build
```

It seems related to: https://github.com/webpack/webpack-cli/issues/607 

I updated webpack-cli to `^3.1.2` and it works fine.

**Comment by ilia-luk** [comment] 2018-10-24 14:16
> I have the same issue using 2.0.181010 branch and below Dockerfile:
> 
> ```
> FROM node:6 as build
> 
> RUN npm install -g cross-env
> ADD . /bitshares-ui
> WORKDIR /bitshares-ui
> RUN cross-env npm install --env.prod
> RUN npm run build
> ```
> It seems related to: [webpack/webpack-cli#607](https://github.com/webpack/webpack-cli/issues/607)
> 
> I updated webpack-cli to `^3.1.2` and it works fine.

worked for me

**Comment by sschiessl-bcp** [comment] 2019-03-19 10:21
Resolved by updating dependencies like suggested in #2160 (done manually outside of PR)

**Closed by sschiessl-bcp** 2019-03-19 10:21 UTC
