### ISSUE TITLE
Add Button to copy "Address"

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#234] opened 2017-08-09 18:36 UTC
this may sound very basic, but many crypto users have no idea that the user name = address. 

suggestion: add a "Copy Address" + with an info on mouse over "Your Address = $NAME".

edit: added this issue the other day actually... please close

**Comment by landry314** [comment] 2017-08-09 20:10
You can close your own issue. Look below to the left of the green comment button.

Before you do so, it would be good to refer to the issue that you are saying it is a duplicate of by typing the # sign then the issue number.

**Comment by wmbutler** [comment] 2017-08-10 19:17
#187 addresses this.

**Closed by wmbutler** 2017-08-10 19:17 UTC
Labels: duplicate
