### ISSUE TITLE
Account history only requests first 100 items

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1665] opened 2018-07-05 11:52 UTC
**Describe the bug**
Account history (activity) page only tries to get the first 100 items of history, regardless of server capacity.

**To Reproduce**
1. Go to "Activity" tab of dashboard
2. The page only loads 100 items
3. Clicking on the arrow at the bottom doesn't trigger further loading action

**Expected behavior**
UI should try to load more history.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Related code: 
https://github.com/bitshares/bitshares-ui/blob/ad40a31fd4fc042f25445f0d71b8cbdf8c89ee84/app/components/Account/RecentTransactions.jsx#L174-L183
https://github.com/bitshares/bitshares-ui/blob/ad40a31fd4fc042f25445f0d71b8cbdf8c89ee84/app/components/Account/RecentTransactions.jsx#L241-L247

Related issue:
#1349 was also related to only loading first 100 items, but the processing logic may be different.

**Comment by abitmore** [comment] 2018-07-05 12:07
It was for better performance, because API servers had performance issues when fetching data which is not latest (which has been fixed in a recent release).

Another thing is it requires too much RAM for API nodes to track a lot of account history data. I've created a pull request to track less data by default: https://github.com/bitshares/bitshares-core/pull/1120.

**Comment by startailcoon** [comment] 2018-07-05 12:29
If I'm not mistaken, wasn't ES something that was mentioned as a solution for this before?

**Comment by wmbutler** [comment] 2018-07-05 18:03
ES should be used to solve this in my opinion.

**Comment by HarukaMa** [comment] 2018-07-05 18:52
The problem here is the UI is only _requesting_ for 100 items, even if the server supports more.

We are writing a websocket proxy to temporarily address that before ES history APIs are in the core by redirecting current account history API requests to a ES backend, and found out that UI is only requesting for 100 items. When ES APIs are officially online this needs to be changed after all.

**Comment by wmbutler** [comment] 2018-07-05 19:04
I don't fully agree...why stress out nodes for >100 items when ES will handle it with a sweat? I think limiting the requests to 100 for direct to the node will provide incentive for ES to become the preferred method. This is important for us to scale in a responsible manner.

**Comment by HarukaMa** [comment] 2018-07-05 20:38
Abit has stated that the performance issue has been fixed in a recent release. @abitmore could you confirm it?

The second point he states will NOT stress the nodes more as it's a server-side configuration.

**Comment by abitmore** [comment] 2018-07-05 21:34
The was a performance issue in bitshares-core which has been fixed with this PR: https://github.com/bitshares/bitshares-core/pull/628, included in `2.0.180328` release.

**Comment by HarukaMa** [comment] 2018-07-05 21:43
Considering the following hardfork all nodes would have the fix, I think the "stressing" doesn't exist anymore and there is no point still request for 100 items only. It also makes full history node almost useless to UI users.

**Comment by wmbutler** [comment] 2018-07-09 18:16
I stand by the fact that we are best served by letting ES do what it does best. The performance increase by querying a true NOSQL datasource is literally an order of magnitude more efficient.

**Comment by startailcoon** [comment] 2018-07-10 20:34
@HarukaMa This is why we have the independent BitShares infrastructure worker.

One of their goals this section is

# Elasticsearch BitShares nodes for public use

Advanced features of the reference wallet require full history and advanced searching capabilities to function smoothly, which requires publicly available nodes with Elasticsearch support. This worker aims to deploy a ES cluster that will be accessible through all deployed infrastructure nodes.

This will greatly simplify the workflow of developers and business administration for BitShares and enable easy access to statistical data processing and charting.

----
Source: https://www.bitshares.foundation/workers/2018-07-infrastructure

**Comment by startailcoon** [comment] 2018-07-29 19:56
Duplicate of #68

**Closed by startailcoon** 2018-07-29 19:56 UTC
Labels: proposed feature

**Comment by abitmore** [comment] 2018-07-29 22:54
@startailcoon I didn't see why it's a duplicate. Looks like #68 is about market history, this issue is about account history.

Actually #68 is getting too long, and there are a lot of unrelated discussions inside. I think it's better to start a new issue with clear user story and requirement specifications, like this one.

**Comment by startailcoon** [comment] 2018-07-30 17:55
ES Wrapper call implemented as `get_account_history`. https://eswrapper.bitshares.eu/apidocs/#!/wrapper/get_account_history

**Comment by clockworkgr** [comment] 2018-07-30 18:43
also available:

http://bts-es.clockwork.gr:5000/apidocs/#!/wrapper/get_account_history

**Comment by startailcoon** [comment] 2018-07-30 18:48
@clockworkgr no need to post urls for ES APIs here. Should be collected on #1734 for the UI ES wrapper.

**Comment by clockworkgr** [comment] 2018-07-30 18:54
Oh ok... I looked at both issues but I saw you posted it here so wanted to provide an alternative :)

**Comment by wmbutler** [comment] 2018-07-31 03:34
Trying to figure out how to estimate this.
