### ISSUE TITLE
[44.5][calvinfroedge][3][startailcoon] Withdraw Modal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#588] opened 2017-10-16 02:19 UTC
## Notes
- [x] Symbol/Asset is a dropdown + typeahead. Only assets with (a) balances (b) gateways, open.* etc (c) BTS  would appear in this list.
- [x] The gateway cannot be chosen by the end user. It is automatically set based upon the asset choice.
- [x] Estimated value is based upon the users preferred currency choice.
- [ ] Address is validated per currency (is the gateway responsible for this validation)?
- [x] If the user chooses to withdraw BTS, the gateway field does not need to be displayed.
- [x] Available balance is clickable
- [x] Available balance is white unless the value in the quantity box > available balance (with fees taken into consideration)
- [x] User should be able to enter into estimated value if desired

![screen shot 2017-10-15 at 9 46 14 pm](https://user-images.githubusercontent.com/1254810/31593123-52140764-b1f2-11e7-89bd-e45e710f42a1.png)

**Comment by landry314** [comment] 2017-10-16 11:26
I wouldn't call it "Symbol", I think "Coin" or "Currency" is better. You aren't withdrawing the symbol for the coin but rather the coin itself.

**Comment by btsfav** [comment] 2017-10-16 11:38
we trade more than coins or currency, so I think symbol is fine. how do other trading platform name the assets?

**Comment by landry314** [comment] 2017-10-16 12:05
But you can't withdraw tokens or bitAssets here, only digital coins held by a gateway.

**Comment by btsfav** [comment] 2017-10-16 12:07
EOS / OMG are tokens for example

**Comment by landry314** [comment] 2017-10-16 12:16
oh, you are right!

**Comment by diogo-gomes** [comment] 2017-10-30 21:03
@btsfav 
> we trade more than coins or currency, so I think symbol is fine. how do other trading platforms name the assets?

What do you think replace `Symbol` with `Asset`?

**Comment by calvinfroedge** [comment] 2017-11-26 17:05
@svk31 Is there a typeahead component which already exists in the codebase? Otherwise I can make one but don't want to duplicate work.

**Comment by calvinfroedge** [comment] 2017-11-26 23:48
So I understand what the modal is supposed to look like, but there are some changes here before we get to that point...

<img width="1176" alt="withdraw" src="https://user-images.githubusercontent.com/632938/33245794-47958e8a-d2da-11e7-9ee9-b18eb49ef71a.png">

Basically the step before the modal will have to change a bit, right? Do we know exactly how that part of the UX will change?

@wmbutler

**Comment by wmbutler** [comment] 2017-11-28 04:51
@calvinfroedge you can leave that screen as is. Your modal will be called separately. I don't think we can just remove this screen. As a matter of fact, we are going to want to keep this for a period of time as a fallback option.

**Comment by calvinfroedge** [comment] 2017-12-04 19:41
I need to bump this to next sprint @wmbutler

**Comment by calvinfroedge** [comment] 2017-12-09 23:18
@wmbutler @startailcoon Please let me know how this is looking on the typeahead...

![typeahead](https://user-images.githubusercontent.com/632938/33800419-5b6b7810-dd0d-11e7-81f1-8b25ecf7a059.gif)

@svk31 Should the onSelect just return the symbol? i.e. `OPEN.BTC`?

**Comment by wmbutler** [comment] 2017-12-14 22:45
@calvinfroedge add needed hours to this.

**Comment by wmbutler** [comment] 2018-01-03 02:15
@calvinfroedge please try to have this out by Jan 4. This is an important feature. Add enough hours to represent the time you put into it.

**Comment by startailcoon** [comment] 2018-01-05 08:06
Spent aprox. ~2 hours on this issue, but it still needs more work before it's done.

**Comment by startailcoon** [comment] 2018-01-10 20:27
@calvinfroedge are you doing work on this or do you wish me to dive into it further?

**Comment by calvinfroedge** [comment] 2018-01-11 20:12
@startailcoon I will continue working on it

**Comment by wmbutler** [comment] 2018-01-12 01:49
@calvinfroedge release date is 1/15. Hope you are able to have this by the 13th because this will need extensive testing. We have ample budget so go to it and keep your hours. This is a big one.

**Comment by wmbutler** [comment] 2018-01-27 15:45
## Notes
- [ ] Only show assets in the dropdown if your account contains > 0 of that asset
- [ ] Limit dropdown contents to 5 in the typeahaed.
- [ ] Typeahead should display as a menu below input field

![test](https://user-images.githubusercontent.com/1254810/35473462-9d9920e8-0346-11e8-999f-e343e06b6f40.gif)


- [ ] Estimated value is failing to populate

![withdraw](https://user-images.githubusercontent.com/1254810/35473444-6cb10b62-0346-11e8-92b6-83bf21ec6b85.gif)

- [ ] Fixed height and width on the modal (see deposit modal for example.
- [ ] Header on Withdraw Modal (see deposit modal for example.

**Comment by startailcoon** [comment] 2018-01-30 20:19
A few issues I've found

- [ ] Selecting an asset that doesn't work (no valid gateway?) displays nothing. Should show an error.
- [ ] Should BTS be listed for withdrawal?
- [ ] Clicking the arrow on `Gateway` doesn't open the list, clicking in the dropdown does.
- [ ] "Estimated value" field shouldn't be editable
- [ ] Display warning when `Quantity` is larger than available.
- [ ] Move "Withdraw To Address" error to right margin abow input
- [ ] Don't enable `Withdraw` button if there is an error, like Address or Quantity.
- [ ] `Fee` dropdown goes beyond screen when the height is not enough to display all available.
- [ ] Add padding between `Fee` and `Gateway Fee` when screen is narrow. 
- [ ] `Fee` doesn't update on `Memo` input.

### On Submit
- [ ] Cancel on unlock or confirm should bring back the Withdraw Modal with the inputted data

### On Dashboard
- [ ] View Withdraw button for each withdrawable asset to the new modal

**Comment by calvinfroedge** [comment] 2018-01-31 16:05
@startailcoon

**Should BTS be listed for withdrawal?** 

I think BTS should be listed for withdrawal, as at least at some other places have supported BTS. Sending BTS from one user to another feels very different from "withdrawing" to an external exchange like polo.

**"Estimated value" field shouldn't be editable**

This was part of the original request specified by @wmbutler (That estimated value should be specifiable by the user). This makes sense especially for assets that don't have sufficient market depth to give a quote.

**Display warning when Quantity is larger than available.**

The field is highlighted in red, I agree adding an error is a good idea.

**Fee doesn't update on Memo input.**

Should it? Does adding a memo increase the fee?

**Thanks for feedback!!! Good ideas!**

**Comment by wmbutler** [comment] 2018-02-01 02:09
@calvinfroedge the fee is variable based on the contents of the memo. That's how we keep the blockchain from getting spammed with massive memos.

**Comment by calvinfroedge** [comment] 2018-02-01 03:06
@wmbutler Understood!

**Comment by startailcoon** [comment] 2018-02-12 05:01
Unless Calvin notify us, I will pick up this task for the next milestone.

**Comment by wmbutler** [comment] 2018-02-12 05:07
@startailcoon please do. I've reached out to Calvin three times in the past week with no response.

**Comment by startailcoon** [comment] 2018-02-19 12:27
@calvin notified me on friday that he would submit changes/updates to this still. I'm still waiting for these changes.

I'm still able to take over if necessary.

**Comment by calvinfroedge** [comment] 2018-02-19 13:51
Working on this all day today

**Comment by calvinfroedge** [comment] 2018-02-19 17:23
@startailcoon 

"Clicking the arrow on Gateway doesn't open the list, clicking in the dropdown does."

This is actually a complex issue. The problem is we're using an actual HTML dropdown for the gateway selection, and it's literally impossible to open a select programmatically. 

We need to implement a custom select (kind of like the typehead, but obviously different) or we need to host that icon somewhere that we can use it in a stylesheet as the select background image. I kind of think it should be a separate issue as I can see spending several hours on this very stupid issue.

**Comment by calvinfroedge** [comment] 2018-02-19 19:15
@wmbutler @startailcoon @svk31 

Many of the outstanding issues were closed. A few that remain I would really prefer if we could handle separately. Hours updated.

**Comment by startailcoon** [comment] 2018-02-19 20:50
Adding 1 hour for review

**Comment by wmbutler** [comment] 2018-02-27 01:11
- [ ] User needs to be able to click on the actual icon in the typeahead (@AustinAmoruso we have a number of needed fixes on this. Since you created it, can you please take a look at this ASAP) ?
- [ ] Value in BTS is not calculated properly for RUDEX.STEEM. I entered .5 STEEM and the the BTS value is calculated at .078 BTS. Should be closer to say, $7.80. Maybe just a precision issue?
- [ ] When the withdraw modal is chosen, there is a long lag in bringing up the modal. Can you instead hide the right menu, present the modal, and then show a loading indicator? This would manage expectations better.

**Comment by calvinfroedge** [comment] 2018-02-27 16:30
@wmbutler 

1) User needs to be able to click on the actual icon in the typeahead -> I added a fix for this on my branch, it's just adding the click event to the chevron icon

2) Value in BTS is not calculated properly for RUDEX.STEEM -> The problem here was for assets with precision < 0

**Comment by calvinfroedge** [comment] 2018-02-27 17:41
@wmbutler I've fixed the problem regarding loading time required for assets in the typeahead, so I think that resolves the third point.

**Comment by wmbutler** [comment] 2018-02-27 21:29
One last comment in the PR regarding precision and estimation. I think we should leave the estimated value input field out for now. It's inaccurate in a variety of situations.

**Comment by wmbutler** [comment] 2018-02-28 14:14
- [ ] Not properly warning user of insufficient balance
![withdraw](https://user-images.githubusercontent.com/1254810/36792185-6e9233ca-1c5f-11e8-898e-633cbe967574.gif)

**Comment by wmbutler** [comment] 2018-02-28 14:17
- [ ] Incorrectly stating that there are no gateways eligible for this withdrawal when OL is clearly available.

![ol](https://user-images.githubusercontent.com/1254810/36792285-cfc7df00-1c5f-11e8-987a-8fdd78a533eb.gif)

**Comment by wmbutler** [comment] 2018-02-28 14:18
- [ ] Withdraw modal takes about 5 seconds to appear. What is causing this? Can you background this operation so the user doesn't have to wait for the modal?

**Comment by calvinfroedge** [comment] 2018-02-28 15:18
@wmbutler 

I resolved the issue about balance warning, was also due to precision issue. I think your other two issues must both be related to calling the gateways.

**Comment by wmbutler** [comment] 2018-02-28 15:42
We are calling OL endpoint in triplicate.

![calls](https://user-images.githubusercontent.com/1254810/36796650-a66c2f42-1c6b-11e8-929d-3234ebc4d78c.gif)

**Comment by wmbutler** [comment] 2018-02-28 15:48
![calls](https://user-images.githubusercontent.com/1254810/36796973-756d24e0-1c6c-11e8-8447-3a174e063e38.gif)

**Comment by calvinfroedge** [comment] 2018-02-28 16:21
Extra network calls should no longer be happening...please check your local branch to see if that resolved your load lag issue

**Comment by wmbutler** [comment] 2018-02-28 16:40
- [ ] Placeholder should say "Search for Asset to withdraw"

![screen shot 2018-02-28 at 10 40 02 am](https://user-images.githubusercontent.com/1254810/36799906-d81482a8-1c73-11e8-84eb-d791d3e62cd6.png)

**Comment by wmbutler** [comment] 2018-02-28 16:44
- [ ] No gateways available to handle this withdrawal bug still exists. You must own OPEN.BTC to test this.

**Comment by AustinAmoruso** [comment] 2018-02-28 20:40
@wmbutler Sorry for the delay on responding I will take a look at this tomorrow to fix the interaction issue.

**Comment by calvinfroedge** [comment] 2018-02-28 20:42
I think it's fixed already

**Comment by AustinAmoruso** [comment] 2018-02-28 20:46
Well then the first rule of IT has worked in my favor wait to see if the issue resolves itself. But honestly I'm sorry I was so slow to respond will try to be more expedient in the future. 
@calvinfroedge Thank you for the heads up.

**Comment by wmbutler** [comment] 2018-02-28 22:50
@AustinAmoruso thanks for checking back in. I believe you have @startailcoon or @ahdigital to thank for that.

**Closed** 2018-03-01 20:39 UTC
Labels: feature, high priority
